src/operator/controllers/intents_reconcilers/kafka_acls.go

Only minor cosmetic change to improve code readability

Improved Kafka reconclier readability

---

README.md

Alternative readme

---

src/operator/controllers/intents_reconcilers/external_network_policy_test.go
src/shared/testbase/testsuitebase.go

Added some conditional waits in external netpol tests and in base test suite to fix flakiness

Fixed external network policies test flakiness

---

src/shared/serviceidresolver/serviceidresolver.go

Make GetOwnerObject public so it is require-able by other projects

Make GetOwnerObject public 

---

.github/workflows/golangci-lint.yml
src/operator/api/v1alpha1/otterize_labels.go
src/operator/controllers/intents_reconcilers/kafka_acls.go
src/operator/controllers/intents_reconcilers/kafka_acls_test.go
src/operator/controllers/intents_reconcilers/network_policy_test.go
src/operator/controllers/intents_reconcilers/pods_test.go
src/operator/controllers/kafkaacls/intentsAdmin.go
src/operator/controllers/kafkaacls/serversStore.go
src/operator/controllers/kafkaserverconfig_controller_test.go
src/operator/main.go
src/shared/testbase/testsuitebase.go

Add golangci-lint workflow

---

.github/workflows/golangci-lint.yml
src/operator/api/v1alpha1/intents_types.go
src/shared/otterizecloud/graphqlclient/generated.go

This PR updates the intents operator to report intents using the new format, which does not use the IntentBody format.

Report intents using new GraphQL IntentInput

---

src/operator/controllers/intents_reconcilers/otterizecloud/cloud_api.go
src/operator/main.go
src/shared/otterizecloud/graphqlclient/generated.go
src/shared/otterizecloud/graphqlclient/genqlient.graphql
src/shared/otterizecloud/mocks/mock_cloud_api.go

This PR makes the intents operator report its configuration to the cloud at start

Reporting intents operator configuration to the cloud

---

src/operator/controllers/intents_reconcilers/otterizecloud/cloud_api.go
src/operator/controllers/intents_reconcilers/otterizecloud/status_report.go
src/operator/main.go
src/shared/otterizecloud/graphqlclient/generated.go
src/shared/otterizecloud/graphqlclient/genqlient.graphql
src/shared/otterizecloud/mocks/mock_cloud_api.go
src/shared/otterizecloud/otterizecloudclient/config.go

Periodically report connection to cloud, so the intents operator component will be presented as 'connected' to the user.

Periodically report connection to cloud

---

src/shared/otterizecloud/otterizecloudclient/cloud_client.go

Set API version to v1beta

---

src/operator/main.go

Since #123, intents operator would not report applied intents to cloud as the cloud client was not initialized correctly.

Fix bug where intents operator would not report applied intents to cloud

---

.gitattributes
.gitmodules
src/go.mod
src/go.sum
src/shared/otterizecloud/graphqlclient/generate.go
src/shared/otterizecloud/graphqlclient/genqlient.yaml
src/shared/otterizecloud/graphqlclient/schema.graphql

Load graphql schema from staging server on go generate

Load graphql schema from staging server on go generate

---

src/operator/controllers/intents_reconcilers/otterizecloud/cloud_reconciler.go
src/operator/controllers/intents_reconcilers/otterizecloud/status_report.go
src/operator/controllers/kafkaserverconfig_controller.go
src/operator/main.go

This PR fixes a "context deadline exceeded" error when trying to connect to Otterize Cloud.

Fixed timeout issue when connecting to otterize cloud

---

src/operator/controllers/intents_reconcilers/network_policy.go

This PR is meant to only split the Reconcile function to smaller one, no logic changes.

Readability improvement in network policy reconciler

---

src/shared/istiopolicy/creator.go
src/shared/istiopolicy/creator_test.go

Support HTTP resource protection using Istio Authorization Policies

Add HTTP enforcement

---

src/operator/config/rbac/role.yaml
src/operator/controllers/intents_reconcilers/otterizecloud/intents_input_matcher.go
src/shared/istiopolicy/creator.go
src/shared/istiopolicy/creator_test.go
src/shared/otterizecloud/graphqlclient/generated.go
src/shared/otterizecloud/graphqlclient/schema.graphql

Fix missing permission for deleting istio policies and add a test to this function.
This PR also updates GraphQL schema files to the latest changes in API and fix the relevant test.
It also fixed one test in istio policy creator who had a missing assertion.

Fix delete all permission

---

.github/workflows/build.yaml
.github/workflows/netpol-e2e-test.yaml

Add e2e test for basic intents and netpol flow

Add e2e test for basic intents and netpol flow

---

src/operator/api/v1alpha2/intents_types.go
src/operator/controllers/intents_reconcilers/istio_policy.go
src/operator/controllers/intents_reconcilers/otterizecloud/cloud_reconciler_test.go
src/shared/istiopolicy/creator.go
src/shared/istiopolicy/creator_test.go
src/shared/istiopolicy/tools.go
src/shared/otterizecloud/graphqlclient/generated.go
src/shared/otterizecloud/graphqlclient/schema.graphql
src/shared/serviceidresolver/serviceidresolver.go
src/shared/serviceidresolver/serviceidresolver_test.go
src/watcher/reconcilers/pods.go

Report when pod is missing Istio sidecar to intents status, and ignore its policies.

Report missing sidecar

---

src/operator/main.go
src/shared/otterizecloud/graphqlclient/generated.go
src/shared/otterizecloud/graphqlclient/schema.graphql

Report the status of istio enforcement

Report istio enforcement config

---

src/exp/istiopolicy/creator.go
src/exp/istiopolicy/creator_test.go
src/operator/api/v1alpha2/intents_types.go
src/operator/controllers/intents_reconcilers/istio_policy.go
src/operator/controllers/intents_reconcilers/otterizecloud/cloud_reconciler_test.go
src/operator/controllers/intents_reconcilers/otterizecloud/intents_input_matcher.go
src/shared/otterizecloud/graphqlclient/generated.go
src/shared/otterizecloud/graphqlclient/schema.graphql
src/shared/serviceidresolver/serviceidresolver.go
src/watcher/cmd/main.go
src/watcher/reconcilers/pods.go

Report missing sidecar for server

---

src/exp/istiopolicy/creator.go

When using `DeleteAllOf` with Istio authorization policies, some policies were not found, even though they exist.
This may happen due to the difference between Istio CRD version `v1` and their Go SDK version which is only `v1beta1`.
This PR replaces the delete all with list & delete operations.

Use delete with list

---

src/operator/main.go
src/shared/telemetries/telemetriesgql/generated.go
src/shared/telemetries/telemetriesgql/schema.graphql
src/shared/telemetries/telemetrysender/config.go
src/shared/telemetries/telemetrysender/global_sender.go
src/shared/telemetries/telemetrysender/sender.go

Align keys and variables related to telemetry with the new schema and use the agreed terminology.

Align telemetry related variables and keys with the new schema

---

src/operator/api/v1alpha2/intents_types.go
src/operator/controllers/intents_reconcilers/crd_validator.go
src/operator/controllers/intents_reconcilers/istio_policy.go
src/operator/controllers/intents_reconcilers/pods.go
src/operator/controllers/istiopolicy/creator.go
src/operator/controllers/istiopolicy/creator_test.go
src/watcher/reconcilers/pods.go

Comment fixes, typos, tiny refactors

Tweaks iteration

---

src/shared/telemetries/telemetrysender/anonimize.go
src/shared/telemetries/telemetrysender/anonymize_test.go

Fix the use of sha256 in the `Anonymize` function. Add tests to check it does everything it needs to do.

Fix anonymize function and add tests

---

.github/workflows/build.yaml
.github/workflows/netpol-e2e-test.yaml
.github/workflows/release-tag.yaml

Changes required to move to GCR from ECR

Moving to GCR

---

.github/workflows/netpol-e2e-test.yaml

Disable telemetry on e2e tests

Disable telemetry on e2e tests

---

src/operator/controllers/intents_reconcilers/otterizecloud/cloud_reconciler_test.go

This PR also adds a few tests for edge cases for formatting and errors. Now, each test doesn't cost extra time so we can afford it.

Use mockgen in cloud tests

---

.github/workflows/netpol-e2e-test.yaml
.github/workflows/test-bashrc.sh

Replace sleep with retry mechanism function

Fix flaky E2E tests

---

src/operator/api/v1alpha2/intents_types.go
src/operator/controllers/protectedservices_controller.go
src/operator/controllers/protectedservices_controller_test.go

Create default deny policies for protected services
Documentation will get updated before we release the feature

Create default deny policy for protected services

---

src/operator/controllers/external_traffic/network_policy_reconciler.go
src/operator/controllers/intents_controller.go
src/operator/main.go
src/shared/otterizecloud/graphqlclient/generated.go
src/shared/otterizecloud/graphqlclient/schema.graphql

Report the configuration status of the protected services feature to Otterize Cloud

Report protected services enabled

---

src/operator/main.go
src/shared/operatorconfig/config.go

Add cli flag to enable debug logs in the operator

Enable debug logs

---

src/intents-operator.Dockerfile
src/operator/controllers/intents_reconcilers/generate.go
src/shared/otterizecloud/graphqlclient/schema.graphql

Use makefile test command in docker file to standardize the way the tests run with the development process and also generate all required files before testing

Use make test in dockerfile

---

src/shared/otterizecloud/graphqlclient/schema.graphql
src/shared/telemetries/telemetriesgql/generated.go
src/shared/telemetries/telemetriesgql/schema.graphql

Update operator shared library schema.

Update to lateset graphql schema

---

src/operator/api/v1alpha2/clientintents_webhook.go

Fixed bug where ClientIntents v1alpha3 conversion webhook would incorrectly convert the intent type

Fix bug where ClientIntents v1alpha3 conversion webhook would incorrectly convert the intent type

---

src/operator/main.go
src/shared/otterizecloud/graphqlclient/schema.graphql
src/shared/telemetries/telemetriesgql/generated.go
src/shared/telemetries/telemetriesgql/schema.graphql
src/shared/telemetries/telemetrysender/config.go
src/shared/telemetries/telemetrysender/global_sender.go

Send active telemetry periodically.

Periodically send active component telemetry

---

src/operator/api/v1alpha3/clientintents_types.go
src/shared/otterizecloud/graphqlclient/generated.go
src/shared/otterizecloud/graphqlclient/schema.graphql

Support for AWS-typed intents report to Otterize cloud

Support for AWS-typed intents report to Otterize cloud

---

src/operator/api/v1alpha3/clientintents_types.go
src/shared/otterizecloud/graphqlclient/generated.go
src/shared/otterizecloud/graphqlclient/schema.graphql

Update Cloud API graphql

---

src/operator/controllers/intents_controller.go
src/operator/main.go
src/shared/operatorconfig/config.go

Change the flag name so it's consistent with the other reconcilers flags.

Change `enableDatabaseCredentialsCreation` flag name to `enableDatabasePolicyCreation`

---

.github/workflows/build.yaml
.github/workflows/golangci-lint.yml
.github/workflows/release-tag.yaml
src/intents-operator.Dockerfile
src/shared/testbase/testsuitebase.go

Prior to this PR, the intents operator would only be built for AMD64. Now it is also built for ARM.

Multiplatform build for ARM alongside AMD64

---

src/shared/operatorconfig/config.go

Make every configuration key configurable with environment variable.

Make every configuration key configurable with environment variable

---

src/operator/main.go
src/shared/otterizecloud/graphqlclient/generated.go
src/shared/otterizecloud/graphqlclient/schema.graphql
src/shared/telemetries/telemetriesgql/schema.graphql

Upload egress enforcement status as part of the operator enforcement configuration upload
Egress is an experimental …

Support presentation of Egress enforcement in Otterize Cloud

---

.github/workflows/allowDNS.yaml
.github/workflows/netpol-e2e-test.yaml

Add a basic e2e test for egress network policy creation.

Add a basic e2e test for egress network policy creation.

---

src/operator/api/v1alpha3/clientintents_types.go
src/operator/controllers/intents_reconcilers/cloud_reconciler_test.go
src/shared/otterizecloud/graphqlclient/generated.go
src/shared/otterizecloud/graphqlclient/schema.graphql
src/shared/telemetries/telemetriesgql/schema.graphql

This PR support uploading and presenting DNS intents on Otterize Cloud

Support presenting DNS intents on Otterize cloud

---

src/operator/controllers/intents_reconcilers/kafka_acls_test.go

For better understanding of the log prints during multiple unit tests during CI/CD this PR add log print for every test.

Add log lines to support debugging flaky Kafka tests

---

src/operator/api/v1alpha2/intents_types.go
src/operator/controllers/external_traffic/network_policy_test.go
src/operator/controllers/external_traffic/network_policy_uploader.go
src/operator/controllers/external_traffic/network_policy_uploader_test.go
src/operator/controllers/istiopolicy/policy_manager.go
src/operator/controllers/istiopolicy/policy_manager_test.go
src/operator/controllers/pod_reconcilers/namespace.go
src/shared/reconcilergroup/reconcilergroup_test.go

Fix a case where istio policies created with the wrong label in their pod selectors

Fix case where Istio policies were created with the wrong label in their pod selectors

---

src/operator/config/rbac/role.yaml
src/operator/controllers/intents_controller.go

Add additional permissions for Google Cloud to the intents operator in order to access config connector CRDS

Add additional permissions for Google Cloud to the intents operator

---

src/operator/controllers/external_traffic/ingress_reconciler.go
src/operator/controllers/external_traffic/network_policy.go
src/operator/controllers/external_traffic/service_uploader.go
src/operator/controllers/external_traffic/service_uploader_test.go
src/operator/controllers/external_traffic/shared.go
src/operator/controllers/external_traffic/svc_reconciler.go
src/operator/controllers/intents_reconcilers/external_traffic_network_policy/external_traffic_network_policy_test.go
src/operator/controllers/intents_reconcilers/external_traffic_network_policy/external_traffic_network_policy_with_no_intents_test.go
src/operator/main.go
src/shared/operator_cloud_client/cloud_api.go
src/shared/otterizecloud/graphqlclient/generated.go
src/shared/otterizecloud/graphqlclient/genqlient.graphql
src/shared/otterizecloud/graphqlclient/schema.graphql
src/shared/otterizecloud/mocks/mock_cloud_api.go
src/shared/telemetries/telemetriesgql/schema.graphql

Support showing services that won't be blocked due to external access policy in shadow mode

Report services that won't be blocked due to external access even when no network policy

---

src/intents-operator.Dockerfile

Build on amd64 and compile for arm64.

Faster cross-platform build for intents-operator

---

README.md

Document Azure & Google Cloud IAM integration in the intents-operator's README.

Update README with Azure & Google Cloud IAM references

---

src/operator/controllers/intents_controller.go
src/operator/main.go
src/shared/otterizecloud/graphqlclient/generate.go
src/shared/otterizecloud/graphqlclient/generated.go
src/shared/otterizecloud/graphqlclient/schema.graphql
src/shared/telemetries/telemetriesgql/generated.go
src/shared/telemetries/telemetriesgql/schema.graphql

Related to #407 - namespaces are now also reported to Otterize Cloud.

Report namespaces for which enforcement is enabled in shadow mode to Otterize Cloud

---

src/operator/Makefile
src/operator/config/crd/k8s.otterize.com_clientintents.patched
src/operator/config/crd/k8s.otterize.com_kafkaserverconfigs.patched
src/operator/config/crd/k8s.otterize.com_postgresqlserverconfigs.patched
src/operator/config/crd/k8s.otterize.com_protectedservices.patched
src/operator/config/crd/kustomization.yaml
src/operator/config/rbac/wildcard-patch
src/operator/config/webhook/kustomization.yaml
src/operator/config/webhook/manifests-patched
src/operator/copy-manifests-to-helm.sh
src/operator/otterizecrds/clientintents-customresourcedefinition.yaml
src/operator/otterizecrds/kafkaserverconfigs-customresourcedefinition.yaml
src/operator/otterizecrds/postgresqlserverconfigs-customresourcedefinition.yaml
src/operator/otterizecrds/protectedservices-customresourcedefinition.yaml

Update kustomize files to avoid manually editing YAML files after they auto generated.

Update Kubernetes manifests auto-generation in the Makefile

---

src/operator/controllers/iam_pod_reconciler/pods.go
src/operator/controllers/intents_reconcilers/cloud_reconciler.go
src/operator/controllers/pod_reconcilers/pods.go
src/operator/main.go
src/shared/operator_cloud_client/cloud_api.go

Fixed bug where single accounts with AWS RolesAnywhere enabled would work incorrectly

Fixed bug where single accounts with AWS RolesAnywhere enabled would work incorrectly

---

src/shared/serviceidresolver/serviceidresolver.go

Prior to this PR, these errors had no stack.

Add stack traces to errors that were not wrapped

---

src/shared/awsagent/rolesanywhere_creds/credentials_provider.go

Prior to this PR, the operator would read only one certificate from the chain.

Fixed bug where the operator in AWS RolesAnywhere multi-account mode would incorrectly present certificate chains to AWS

---

src/operator/copy-manifests-to-helm.sh

Update copy-manifests-to-helm for CRD removal from Helm chart (https://github.com/otterize/helm-charts/pull/209)

Update copy-manifests-to-helm for CRD removal from Helm chart (https://github.com/otterize/helm-charts/pull/209)

---

src/operator/controllers/intents_reconcilers/mocks/mock_service_resolver.go
src/shared/otterizecloud/graphqlclient/generated.go
src/shared/otterizecloud/graphqlclient/schema.graphql
src/shared/serviceidresolver/mocks/mock_service_resolver.go
src/shared/telemetries/telemetriesgql/generated.go
src/shared/telemetries/telemetriesgql/schema.graphql

Update generated GraphQL schema to update the shared code of the telemetries API.

Update generated Graphql schema

---

src/operator/controllers/intents_reconcilers/database/database_reconciler.go
src/operator/controllers/intents_reconcilers/external_traffic_network_policy/external_traffic_network_policy_test.go
src/operator/controllers/intents_reconcilers/external_traffic_network_policy/external_traffic_network_policy_with_no_intents_test.go
src/operator/controllers/intents_reconcilers/mocks/mock_intents_reconciler.go
src/operator/controllers/pod_reconcilers/pods.go
src/operator/controllers/pod_reconcilers/pods_test.go
src/operator/main.go

Handle database intents scenario where pod does not exist at time of intents being applied

Handle database intents scenario where pod does not exist at time of intents being applied

---

src/operator/webhooks/mysqlserverconfigs_webhook.go

Fixing bad type assertion in MySQL webhook

Fixing bad type assertion in MySQL webhook

---

src/shared/databaseconfigurator/mysql/mysql.go
src/shared/databaseconfigurator/postgres/postgres.go
src/shared/databaseconfigurator/postgres/utils.go

This PR resolves a race that may occur when the credentials operator attempts to set user password, for a user that has already been deleted by the intents operator (due to intents being removed).

Ignore user not found errors on alter user password from postgres & mysql integrations

---

src/operator/api/v2alpha1/clientintents_types.go
src/operator/controllers/intents_reconcilers/cloud_reconciler_test.go

Fix a bug where applied intents with kind in their targets wouldn't be reported properly.

Fix a bug where applied intents with kind in their targets wouldn't be reported properly

---

src/operator/controllers/pod_reconcilers/pods.go

Fix annotation-based intents creating a non-existent intent when no annotations were found

Fix intent operator adding annotation intent when not needed

---

src/shared/awsagent/roles.go

This PR fixes a bug on the AWS reconciler, where a null dereference could happen due to missing error handling. 

Bugfix on AWS integration: null dereference on AWS role object due to missing error handling

---

src/operator/controllers/intents_reconcilers/kafka_acls.go

Changing spammy log line to debug

Changing spammy log line to debug

---

src/operator/api/v1alpha3/webhooks.go
src/operator/api/v1alpha3/webhooks_test.go
src/operator/api/v1beta1/webhooks.go
src/operator/api/v1beta1/webhooks_test.go

Improve HTTP conversion logic, so it will handle empty resources list the same way it handles nil list

Improve HTTP conversion logic, so it will handle empty resources list the same way it handles nil list

---

src/operator/main.go

Fix a bug where a race condition between the CRD ensurer and another running operator instance could cause all the reconcilers to fail to watch, while still passing health checks

Fix bug where a race condition could cause the operator to fail but still pass health checks

---

src/operator/main.go
src/shared/operator_cloud_client/cloud_api.go
src/shared/operator_cloud_client/intent_events_sender.go
src/shared/operator_cloud_client/status_report.go
src/shared/otterizecloud/graphqlclient/generate.go
src/shared/otterizecloud/graphqlclient/generated.go
src/shared/otterizecloud/graphqlclient/genqlient.graphql
src/shared/otterizecloud/graphqlclient/genqlient.yaml
src/shared/otterizecloud/graphqlclient/schema.graphql
src/shared/otterizecloud/mocks/mock_cloud_api.go
src/shared/otterizecloud/otterizecloudclient/config.go
src/shared/telemetries/telemetriesgql/schema.graphql

Report intent statuses and events to the cloud to provide a better understanding of enforcement state

Report intent statuses and events to the cloud to provide a better understanding of enforcement state

---

src/shared/awsagent/roles.go

This PR fixes a bug in AWS IAM Roles Anywhere integration: when loading the Roles Anywhere profiles, the last page of profiles was not stored into the in-memory cache. As a result, the credentials-operator would attempt to re-create profiles for roles that already have profiles, causing an error: "provided role ARN should be unique across all profiles".

Bugfix in AWS IAM Roles Anywhere: last page of IAM roles anywhere profiles was not loaded into cache

---

src/operator/controllers/validating_webhook_configurations_controller.go

This PR fixes a bug in the validating webhook configuration controller: catch Kubernetes API Confict errors and retry on them. 

Bugfix in validating webhook configuration controller: catch and retry update on Conflict errors

---

src/operator/controllers/external_traffic/network_policy.go
src/operator/controllers/intents_reconcilers/istio_policy.go
src/operator/controllers/intents_reconcilers/networkpolicy/reconciler.go
src/operator/controllers/intents_reconcilers/pods.go
src/operator/controllers/pod_reconcilers/pods.go
src/shared/clusterutils/clusterid.go
src/shared/reconcilergroup/reconcilergroup.go

Fix wrong handling of kubernetes errors that caused spam error logs

Fix wrong handling of kubernetes errors that caused spam error logs

---

src/shared/serviceidresolver/podownerresolver/podownerresolver.go

Improve pod resolution performance by increasing cache size of "pod to owner" to one hour.

Improve pod owner resolution performance

---

src/operator/controllers/intents_controller.go
src/operator/controllers/intents_controller_test.go
src/operator/controllers/intents_reconcilers/cloud_reconciler.go
src/operator/controllers/intents_reconcilers/telemetry_reconciler.go
src/operator/main.go

Improve intent reconciliation speed by moving cloud and telemetry reporters out of the main intent group reconciler

Improve intent reconciliation speed by moving cloud and telemetry reporters out of the main intent group reconciler

---

src/operator/api/v2alpha1/clientintents_types.go
src/operator/config/crd/k8s.otterize.com_clientintents.patched
src/operator/config/crd/k8s.otterize.com_clientintents.yaml
src/operator/otterizecrds/clientintents-customresourcedefinition.yaml

Set `KubernetesTarget.Kind` yaml and json tags to `omitempty` for prettier describe output

Set `v2alpha1.KubernetesTarget.Kind` yaml and json tags to `omitempty` for prettier describe output

---

src/operator/controllers/intents_reconcilers/iam/iampolicyagents/azurepolicyagent/agent.go
src/operator/controllers/intents_reconcilers/iam/iampolicyagents/azurepolicyagent/agent_customroles_test.go
src/operator/controllers/intents_reconcilers/iam/iampolicyagents/azurepolicyagent/agent_identities_test.go
src/operator/controllers/intents_reconcilers/iam/iampolicyagents/azurepolicyagent/agent_keyvault_test.go
src/shared/azureagent/agent.go
src/shared/azureagent/azureclients.go
src/shared/azureagent/customroles.go
src/shared/azureagent/mocks/azureclients.go
src/shared/otterizecloud/graphqlclient/schema.graphql
src/shared/telemetries/telemetriesgql/schema.graphql

Validate scope before creating Azure custom roles - this will prevent cleanup errors and invalid role assignments

Validate scope before creating Azure custom roles

---

src/shared/azureagent/customroles.go

Create custom roles at subscription scope to allow cross resource group access

Create custom roles at subscription scope

---

src/shared/azureagent/customroles.go
src/shared/azureagent/utils.go
src/shared/azureagent/utils_test.go

Prevent unnecessary updates to Azure custom roles when the actions and data actions are the same. 

Prevent duplicate azure custom role update

---

src/operator/controllers/external_traffic/network_policy.go

Added a single retry for external network policy creation in case of already exists error. Will try to re-fetch existing policy before eventually returning an error now.

Solved bug where creating an external network policy would sometimes error with an "Already Exists" K8s error

---

src/shared/databaseconfigurator/postgres/postgres.go
src/shared/databaseconfigurator/postgres/utils.go

Adding an additional check for database names on top of the current method (checking for Postgres error code) when trying to revoke permissions.

Fixing no authrization error for PostgreSQL in managed databases 

---

src/operator/main.go
src/shared/clusterutils/clusterid.go
src/shared/k8sconf/k8sconf.go
src/webhookserver/main.go

Proxy would also be used for control plane traffic, which was not functional in some environments.

Only use HTTP_PROXY/HTTPS_PROXY for outgoing traffic

---

.github/workflows/netpol-e2e-test.yaml

Update netpol egress E2E test to accommodate changes in egress network policies by default allowing DNS traffic

Update netpol egress E2E test to accommodate changes in egress network policies by default allowing DNS traffic

---

src/operator/controllers/webhook_traffic/network_policy_handler.go
src/operator/controllers/webhook_traffic/network_policy_handler_test.go
src/operator/controllers/webhook_traffic/network_policy_handler_utils_test.go

Fixed 2 bugs:
1. The label length was too long, thus failing the reconcile and creating reconcile loop
2. The network policy did not use the webhook service's target (container) port, so traffic was actually blocked for the service (instead of auto-allowed)

Fixed a bug where auto-allow webhook network policy didn't allow communication to the service target port
