src/shared/serviceidresolver/serviceidresolver.go

Refactoring the `ResolvePodToServiceIdentity` function to call another function that returns the owner object (instead of just the name). This adds flexibility if other dependent projects require the owner's kind as well as the name.

Adding owner object function

---

src/operator/api/v1alpha1/intents_types.go
src/operator/config/crd/k8s.otterize.com_clientintents.yaml
src/operator/controllers/intents_reconcilers/kafka_acls_test.go
src/operator/controllers/kafkaacls/intentsAdmin.go
src/shared/testbase/testsuitebase.go

Previously, Kafka intents with no topics would simply not allow any access. Intents that are not specific about which resources are allowed should allow all access of the kind that isn't specified. For example, a HTTP intent with no HTTP method or path specified just means that you can access using HTTP, to any path and any method.
Similarly, a Kafka intent with no topics or operations specified should create an ACL that allows access to all topics and operations, and a Kafka intent with only the topic name specified should create an ACL that allows all operations for that topic.

Handle Kafka intents with no topics as if they allow all topics

---

src/operator/controllers/intents_reconcilers/otterizecloud/cloud_api.go
src/operator/controllers/intents_reconcilers/otterizecloud/cloud_reconciler.go
src/operator/controllers/kafkaserverconfig_controller.go
src/operator/controllers/kafkaserverconfig_controller_test.go
src/shared/otterizecloud/graphqlclient/generated.go
src/shared/otterizecloud/graphqlclient/genqlient.graphql
src/shared/otterizecloud/graphqlclient/genqlient.yaml
src/shared/otterizecloud/mocks/mock_cloud_api.go

Removed namespace reporting and all its related features (`sync.Map` cache) from cloud reconciler

Removing report namespace route and logic from cloud reconciler

---

src/shared/otterizecloud/otterizecloudclient/cloud_client.go

This PR fixed an error when running without cloud credentials
```
missing cloud integration client ID
```

Fixed error when running without cloud connectivity

---

src/operator/controllers/external_traffic/endpoints_reconciler.go
src/operator/controllers/external_traffic/network_policy.go
src/operator/controllers/intents_controller.go
src/operator/controllers/intents_reconcilers/external_network_policy_test.go
src/operator/controllers/intents_reconcilers/kafka_acls.go
src/operator/controllers/intents_reconcilers/kafka_acls_test.go
src/operator/controllers/intents_reconcilers/network_policy.go
src/operator/controllers/intents_reconcilers/network_policy_test.go
src/operator/controllers/kafkaacls/intentsAdmin.go
src/operator/controllers/kafkaacls/serversStore.go
src/operator/controllers/kafkaserverconfig_controller_test.go
src/operator/main.go

This PR adds the --enable-enforcement=false flag, which can be used in order to disable all the enforcement abilities of the intents operator at once.
If enable-enforcement is true (which is the default), the other flags can be used in order to disable only specific enforcement types (e.g. disable only Kafka ACLs)
Tests:
Added unit tests to verify network policies and Kafka ACLs are not created when enable-enforcement=false

Added enable-enforcement=false flag that disables enforcement globally

---

src/operator/controllers/intents_reconcilers/otterizecloud/status_report.go
src/operator/main.go

Multiple calls to signal handlers may crush the operator, this PR reuse the context in main to fix it.

Fix signal handler context

---

src/operator/controllers/intents_reconcilers/otterizecloud/status_report.go

Send connection status right on operator start up, so we won't wait until `component-report-interval`  time will end

Send component status on start up

---

src/operator/controllers/intents_reconcilers/pods.go
src/operator/controllers/intents_reconcilers/pods_test.go

This is a fix for the following panic, caused by access to nil annotations map:
```
name=cartservice namespace=otterize-ecom-demo reconcileID="\"72de7012-fbf6-4bb8-93c8-3d796198f06e\""
2023-01-18T13:46:30.010885750Z manager panic: assignment to entry in nil map [recovered]
2023-01-18T13:46:30.010898166Z manager     panic: assignment to entry in nil map
2023-01-18T13:46:30.010900250Z manager 
2023-01-18T13:46:30.010901791Z manager goroutine 289 [running]:
2023-01-18T13:46:30.010905875Z manager sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
2023-01-18T13:46:30.010908666Z manager     /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:118 +0x1f4
2023-01-18T13:46:30.010910333Z manager panic({0x168b360, 0x1adf9f0}) …
```

Fix panic on client intents delete for pods that has no annotations

---

src/operator/api/v1alpha2/intents_types.go
src/shared/otterizecloud/graphqlclient/generated.go

The Kafka operation didn't have structured conversion from k8s format to cloud format, just pure string conversation. There was also an missing enum value for Kafka operation. This all caused error when uploading Kafka operation to cloud.
This PR implement the missing value.

Convert Kafka operation enum to cloud format

---

src/operator/controllers/intents_reconcilers/kafka_acls.go
src/operator/controllers/intents_reconcilers/network_policy.go
src/operator/controllers/intents_reconcilers/network_policy_test.go

Since the change in #90 , cross-namespace intents would generate a malformed label. Added test to prevent regression.

Fixed bug where cross namespace intents repeated the namespace name

---

src/operator/controllers/intents_reconcilers/otterizecloud/cloud_reconciler_test.go
src/operator/controllers/intents_reconcilers/otterizecloud/intents_input_matcher.go

This PR improve the testing infrastructure by extending the intents matcher to deep compare all fields of intent sent to cloud. This will enable to test that every field in the CRD object and will support future expanding of our tests.

Support deep comparison of intents cloud object for testing

---

src/operator/controllers/intents_reconcilers/otterizecloud/cloud_api.go
src/operator/main.go
src/shared/otterizecloud/graphqlclient/generated.go
src/shared/otterizecloud/mocks/mock_cloud_api.go

A previous change #104 added the ability to report global enforcement state to Otterize Cloud - this PR adds the ability to report network policy and Kafka ACL enforcement state individually, in addition to the global state.

Report network policy & Kafka ACL enforcement state in addition to global enforcement state

---

src/operator/webhooks/clientintents_webhook.go
src/operator/webhooks/webhook_suite_test.go
src/shared/testbase/testsuitebase.go

Until this PR when applying patch to existing `ClientIntent` the validator checked the old object instead of the new one. It didn't return error when invalid combination of type and topic \ resource where applied, and instead we get failure when applying fix with the correct object. This PR change it to check the new as necessary, the old one is ignored just like we do on delete
Add test that reproduce the bug and make sure we get error

Validate new object on update

---

src/operator/controllers/intents_reconcilers/otterizecloud/cloud_reconciler.go
src/operator/main.go
src/shared/otterizecloud/otterizecloudclient/cloud_client.go
src/shared/otterizecloud/otterizecloudclient/cloud_client_test.go
src/shared/otterizecloud/otterizecloudclient/config.go

Until this PR token source timeout received context with timeout of 10sec from application start.
Since token acquisition happen after 24 hours, it immediately gets a timeout and exit.
This PR create token source with timeout on httpclient, like the package expects the user to do

Fix small timeout in token acquisition

---

src/operator/controllers/intents_reconcilers/otterizecloud/cloud_reconciler.go
src/operator/controllers/intents_reconcilers/otterizecloud/status_report.go
src/operator/controllers/kafkaserverconfig_controller.go
src/operator/main.go
src/shared/otterizecloud/otterizecloudclient/cloud_client.go

This PR replace the default timeout in cloud http client with context timeout for every operation. 
This behavior is more explicit, allow adjusting the value per use case.

Use context timeout instead of HTTP client 

---

src/shared/serviceidresolver/serviceidresolver.go
src/watcher/reconcilers/pods.go

When an owner object is used for resolving the service name (as opposed to service name annotation), then the object is returned. The caller can then use information, such as the GroupVersionKind, on the owner object to better understand the result.

Service identity resolving returns both the name and owner object

---

src/shared/otterizecloud/otterizecloudclient/cloud_client.go
src/shared/otterizecloud/otterizecloudclient/config.go

Support providing custom root CAs when initializing the otterize cloud client.

Support custom root CAs when initializing cloud client

---

src/shared/serviceidresolver/serviceidresolver.go
src/shared/serviceidresolver/serviceidresolver_test.go

The previous logic wasn't compatible with how we really label pods. This change actually fixes the last resolve SA function.
Tests were changed accordingly.

Use builtin intent's function BuildPodLabelSelector to find the right pod in the resolve SA function

---

src/operator/controllers/intents_reconcilers/istio_policy.go
src/shared/istiopolicy/creator.go
src/watcher/reconcilers/pods.go

Pod watcher shouldn't create Istio authorization policies when the pod is missing Service Account or intents are being deleted

Pod watcher ignore policy creation when missing SA or deleted intents

---

src/operator/controllers/intents_reconcilers/istio_policy.go
src/operator/controllers/istiopolicy/tools.go
src/watcher/reconcilers/pods.go

Fix Istio Authorization Policy name. Until this PR the resource got dynamically from AuthorizationPolicy object, which is in single, while the resource definition name is in the plural. The result - istio policies never created.
This commit changes the name of the search target to plural and adds a warning to the logs

Fix Istio CRD name and add log message

---

README.md
src/shared/telemetries/telemetrysender/config.go

Because helm charts with latest tagged images are still out there, we will disable telemetry by default on the operator and keep it on from the helm-chart. By doing so, only new users will send telemetries while the old ones won't.

Turn telemetry off by default

---

src/operator/Makefile
src/operator/config/rbac/role.yaml
src/operator/controllers/intents_controller.go
src/watcher/reconcilers/namespace.go

This change also ensures that Kubebuilder auto-generated manifests are aligned with the latest version of Helm charts.

Add 'update CRD' permission to intents operator

---

README.md
src/operator/Makefile

Allow developers to create a local image, push and deploy it to Minikube without using Otterize's official registry.

Add local docker image generation flow to Makefile

---

src/shared/reconcilergroup/reconcilergroup.go
src/shared/reconcilergroup/reconcilergroup_test.go

The intents operator manager combines multiple reconcilers with a large group of them who watch the resource `ClientIntents`. Those are gathered under the `intents reconciler` using a reconciler group mechanism. 
The current state is that failure in one of them will re-queue the request immediately without handling the rest of the reconcilers. Depending on the random order of reconcilers' registration to the group, there may be reconcilers who won't run in at all if the error in one of the reconciler repeats. For example, a bug in Cloud reconciler may result in not creating NetworkPolicies.
Here is the current list of reconcilers:
* NetworkPolicy
* PodLabel
* CRD validator
* Cloud 
* Kafka ACL 
* Istio policy
It's pretty clear that most of this list is independent of each other. There are …

Decouple reconcilers run results from each other

---

src/operator/controllers/external_traffic/endpoints_reconciler.go
src/operator/controllers/external_traffic/network_policy.go
src/operator/controllers/intents_reconcilers/external_network_policy_with_no_intents_test.go
src/operator/main.go
src/shared/operatorconfig/config.go

When applying a global default deny policy, all traffic to all pods will be blocked, even traffic from an Ingress or LoadBalancer, which is likely intended traffic.
The intents operator can automatically create network policies for external traffic when intents are pointing to a target service. The rationale is that specifying intents for intra-cluster traffic should not block external traffic. See more info here: https://docs.otterize.com/reference/access-controls/network-policies#auto-generating-network-policies-for-external-traffic
This PR adds a disabled-by-default, experimental flag for enabling this behavior _even if no intents point to the service_, which is suitable for use with a global default deny policy. This way, the operator will open up external traffic automatically for …

Add support for creating external traffic policies even if no intents point to the same service

---

src/operator/api/v1alpha2/intents_types.go
src/shared/serviceidresolver/serviceidresolver.go
src/shared/serviceidresolver/serviceidresolver_test.go

The name of the Otterize service is derived from the K8s resource that owns a pod we want to secure. The name of the resource that owns the pod doesn't necessarily have to be a valid DNS name, but it must follow the [RFC 1123 subdomain naming convention](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names).
This means that '.' is a valid character in the deployment name, which poses a challenge when parsing server names and namespaces in client intents format. The dot is used as a separator between the name and the namespace. For example, if the deployment name is `my-application.4.5.0` in the `infra` namespace, we won't be able to tell if `my-application.4.5.0.infra` is a namespaced name or just the name of the deployment without any namespace.
To …

Replace dots with underscore in discovered service name

---

src/operator/api/v1alpha2/intents_types.go
src/operator/controllers/external_traffic/endpoints_reconciler.go
src/operator/controllers/intents_controller.go
src/operator/controllers/intents_reconcilers/external_traffic_network_policy/external_traffic_network_policy_test.go
src/operator/controllers/intents_reconcilers/external_traffic_network_policy/external_traffic_network_policy_with_no_intents_test.go
src/operator/controllers/intents_reconcilers/kafka_acls_test.go
src/operator/controllers/intents_reconcilers/network_policy.go
src/operator/controllers/intents_reconcilers/network_policy_test.go
src/operator/controllers/kafkaserverconfig_controller_test.go
src/operator/main.go
src/operator/webhooks/webhook_suite_test.go
src/shared/testbase/testsuitebase.go
src/watcher/reconcilers/pods.go
src/watcher/reconcilers/pods_test.go

1. Fixed bug where external traffic policies would be erroneously removed when intents from multiple namespaces existed and all intents in one namespace were deleted.
2. The experimental flag, `autoCreateNetworkPoliciesForExternalTrafficDisableIntentsRequirement`, was not taken into account during intent deletion flow, so even when it was enabled, removing all intents would result in external traffic network policies being removed.

Fixed bug where external traffic policies would be erroneously removed when intents from multiple namespaces were deleted

---

src/operator/controllers/external_traffic/endpoints_reconciler.go
src/operator/controllers/external_traffic/ingress_reconciler.go
src/operator/controllers/intents_controller.go
src/operator/controllers/intents_reconcilers/external_traffic_network_policy/external_traffic_network_policy_test.go
src/operator/controllers/intents_reconcilers/external_traffic_network_policy/external_traffic_network_policy_with_no_intents_test.go
src/operator/controllers/intents_reconcilers/mocks/mock_endpoints_reconciler.go
src/operator/controllers/intents_reconcilers/network_policy_test.go
src/shared/otterizecloud/graphqlclient/schema.graphql

Introduces the `EndpointsReconciler` interface. The implementation of this mock for this interface was already pushed and merged in a previous PR but without the type change itself,

Make endpoints reconciler an interface

---

src/operator/api/v1alpha2/intents_types.go
src/operator/controllers/intents_reconcilers/otterizecloud/cloud_reconciler_test.go

Since dots are illegal Otterize service names but are valid deployment names, we replace the dots with underscores when detecting a service name from deployment. 
There is no reason to bring it back internally to dots, especially because we can't know if the real service name had underscores in it in the first place.
(this is already documented)

Don׳t replace underscore with dots

---

src/operator/webhooks/protectedservices_webhook.go
src/operator/webhooks/webhook_suite_test.go

Fixing two errors in Protected Services CRD validation:
1. Only lowercase letters should be allowed
2. The use of the function `Trim` was wrong since it only works at the end of the string
- Those rules will be documented when development will be done and before publishing the feature in our helm chart

Fix protected services validator

---

src/operator/main.go

This PR changes the behavior of when the operator reports ProtectedServicesEnabled to the cloud - instead of always, it now only does it when network policy creation is enabled. The cloud can use this information to determine whether this feature is both supported and will result in network policies being created, when simulating the effects of network policies.

Report ProtectedServicesEnabled only if network policy creation is enabled

---

src/operator/main.go
src/operator/protectedservicescrd/applyProtectedServicesCRD.go
src/operator/protectedservicescrd/protectedservices-customresourcedefinition.yaml
src/operator/webhooks/protectedservices_webhook.go
src/operator/webhooks/webhook_suite_test.go

This PR makes the operator create the ProtectedService CRD if it is missing. This is a temporary measure, as we switch from using Helm charts to manage our CRDs to asking users to apply CRDs prior to installation. Once we do so and that has been released for a while, we will remove this workaround.
Also in this PR: missing webhook to validate that there are no duplicate protected services

Create ProtectedService CRD if missing, add webhook to validate duplicate protected services

---

src/shared/operatorconfig/config.go

This PR renames the flag, so that its new behavior is in line with its name - forgotten in previous PRs. To learn more about the flag, see the comment next to its name in the code.

Rename 'enable-enforcement' flag to 'default-enforcement-state'

---

src/operator/controllers/intents_reconcilers/istio_policy.go

Change the log level of ignoring Istio to debug. It's a very rare use case to both having the will to use Istio enforcement while Istio isn't installed in the cluster and there is no need to spam the logs with this line.

Change Istio ignore log line to debug

---

src/shared/serviceidresolver/config.go
src/shared/serviceidresolver/serviceidresolver.go
src/shared/serviceidresolver/serviceidresolver_test.go

Following https://github.com/otterize/network-mapper/issues/128 , adding support for user-specified annotation for service name override. The default will be `intents.otterize.com/service-name` as it used to be, and it will be configurable through the environment variable: `OTTERIZE_SERVICE_NAME_OVERRIDE_ANNOTATION`. 
After this PR we should update `go.mod` for credentials-operator and network-mapper, And then expose the new env var as an helm chart value. 
https://github.com/otterize/network-mapper/issues/128

Support user specified annotation for service name override

---

src/go.mod
src/shared/telemetries/telemetrysender/config.go
src/shared/telemetries/telemetrysender/global_sender.go
src/shared/telemetries/telemetrysender/sender.go
src/shared/telemetries/telemetrysender/service_counter.go
src/shared/telemetries/telemetrysender/service_counter_test.go

Unique event counter allow to count distinct events and send them as telemetry while using only anonymized and hashed data and send only the distinct count of the event.

Create unique event counter for telemetries

---

src/operator/controllers/intents_reconcilers/external_traffic_network_policy/external_traffic_network_policy_with_no_intents_test.go

This test meant to check no policy is created when external network policy is disabled, there is no state where external network policy is disabled but `AutoCreateNetworkPoliciesForExternalTrafficNoIntentsRequired` is enabled.
The event shouldn't raised since the policy is never created.

Fix test: External network policy when enforcement disabled

---

src/operator/controllers/external_traffic/network_policy_reconciler.go
src/operator/controllers/external_traffic/network_policy_uploader.go
src/operator/controllers/external_traffic/network_policy_uploader_test.go
src/operator/main.go

Until this PR external network policy reconciler was registered always, even when the operator wasn't connected to the cloud.  This resulted in panic due to dereferencing nil pointer of the cloud client.
This PR avoids registration of the reconciler if no cloud client is provided. It also renames it to network policy uploader to avoid confusion with intent network policy reconciler and adds a nice basic test.

Fix bug: External network policy uploader get panic when no cloud client

---

src/operator/controllers/intents_reconcilers/port_network_policy/port_network_policy.go
src/operator/controllers/intents_reconcilers/port_network_policy/port_network_policy_test.go
src/operator/main.go
src/shared/otterizecloud/graphqlclient/schema.graphql
src/shared/telemetries/telemetriesgql/generated.go
src/shared/telemetries/telemetriesgql/schema.graphql

The field `externalNetworkPoliciesCreatedEvenIfNoIntents` seems like a copy-paste error, and isn't used in PortNetworkPolicyReconciler.

Remove unused field in PortNetworkPolicyReconciler

---

src/operator/controllers/kafka_server_config_reconcilers/kafka_server_config_controller_test.go
src/operator/controllers/kafka_server_config_reconcilers/kafka_server_config_reconciler.go
src/operator/controllers/kafkaserverconfig_controller.go

This meant to enable extending the logic of the KSC handling in the same way we handle the rest of Otterize custom resources, with one controller who holds a reconcilers group. 
For easier code review process, this PR only separate the logic into to two files, without renaming or creating the reconciler group. Those changes will be add in future PRs
Also include details of the environment this PR was developed in …

Separate Kafka Server Config logic to controller and reconciler

---

src/operator/controllers/kafka_server_config_reconcilers/kafka_server_config_controller_test.go
src/operator/controllers/kafka_server_config_reconcilers/kafka_server_config_reconciler.go
src/operator/controllers/kafkaserverconfig_controller.go

Create reconciler group for KSC to enable extending its logic with new reconcilers, and also remove the redundant logic who handle the finalizers since the group already implement that as in any other Otterize resource.

Create reconciler group for KafkaServerConfig

---

src/go.mod
src/operator/controllers/kafka_server_config_reconcilers/telemetry_reconciler.go
src/operator/controllers/kafka_server_config_reconcilers/telemetry_reconciler_test.go
src/operator/controllers/kafkaserverconfig_controller.go

Send the count of KafkaServerConfig applied resources as a telemetry, if telemetries are enabled.

Send KafkaServerConfig count telemetry

---

src/operator/controllers/intents_reconcilers/cloud_reconciler.go

This PR fixes a bug where the intents operator would report deleted intents as existing to Otterize Cloud.

Fix bug where intents operator would report deleted intents as existing to Otterize Cloud

---

src/operator/controllers/intents_reconcilers/exp/database.go
src/operator/controllers/intents_reconcilers/exp/database_test.go

Until this PR, database reconciler reports nil pointer when client intents doesn't contain any database type. This cause backend error since the GraphQL mutation doesn't support nil variable. In the case there are no `Database` typed intents there is no database action to perform, so nothing should be done and we can skip the API call.

Fix bug: Empty intents list reported when there are no database intents

---

src/operator/controllers/intents_reconcilers/aws_reconciler.go
src/shared/awsagent/policies.go
src/shared/awsagent/roles.go

Fix bug where IAM policy could be already deleted or non-existent, in the case of a non-IAM ClientIntents, and lead to reconcile error loop.
Also changes the pod annotation into a pod label.
https://github.com/otterize/helm-charts/pull/133
https://github.com/otterize/credentials-operator/pull/93

Fix bug where IAM policy could be already deleted or non-existent, in the case of a non-IAM ClientIntents, and lead to reconcile error loop

---

src/shared/awsagent/policies.go
src/shared/awsagent/roles.go
src/shared/awsagent/types.go

1. The controller tries to create role names that are too long (the AWS limit is 64 characters).
2. The tag check for deletion did not include cluster name, and succeeded on the first correct tag (instead of checking them all).
The too long role name is pretty easy to achieve since it includes a lot of data

Fixes a few bugs in AWS role management:

---

src/operator/controllers/kafka_server_config_reconcilers/kafka_server_config_reconciler.go

The telemetry `KAFKA_SERVER_CONFIG_APPLIED` is reported twice whenever the resource is applied instead of once. It should be handled in the resource's telemetry reconciler, not in the main one.  
Telemetries logic is disabled globally in tests so there is no integration tests for it. It can be reproduce manually by applying the resource.

Fix bug: KSC telemetry reported twice instead of once

---

src/operator/controllers/external_traffic/shared.go
src/operator/main.go

This PR fixes a crash where Ingress resources that had an empty (`{}`) IngressRule would cause the Ingress Service indexer to crash.
```
time="2023-11-22T20:08:46Z" level=info msg="Serving webhook server" host= logger=controller-runtime.webhook port=9443
time="2023-11-22T20:08:46Z" level=info msg="Starting certificate watcher" logger=controller-runtime.certwatcher
E1122 20:08:46.071723       1 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 120 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1c8e420?, 0x3114250})
/go/pkg/mod/k8s.io/apimachinery@v0.27.2/pkg/util/runtime/runtime.go:75 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0008405a0?}) …
```

Fix panic in automatic external traffic handling

---

src/operator/controllers/intents_reconcilers/external_traffic_network_policy/external_traffic_network_policy_test.go
src/operator/main.go

Previously, the readyz/healthz check would not wait for webhook server to start. This would not cause problems in a real scenario as the controller would crash if the webhook server did not start successfully, but in automated testing this could result in the test starting too quickly, before the webhook server is listening, causing intermittent failures.

Fix problem where healthz/readyz would not wait for webhook server to start

---

.github/workflows/golangci-lint.yml
src/operator/controllers/intents_reconcilers/aws_reconciler.go
src/shared/awsagent/agent.go
src/shared/awsagent/policies.go
src/shared/awsagent/roles.go

DeleteOtterizeIAMRole did not check tags correctly, and skipped roles that it did create, while it was supposed to only skip roles not created by it.
Related: https://github.com/otterize/credentials-operator/pull/97

Fix bug where AWS IAM roles were not deleted upon pod termination

---

src/operator/api/v1alpha2/intents_types.go
src/operator/api/v1alpha3/clientintents_types.go
src/operator/config/crd/k8s.otterize.com_clientintents.yaml
src/operator/otterizecrds/clientintents-customresourcedefinition.yaml

The table and operations fields are no longer required for database-typed intents. If no operations are specified it equals to specify `ALL`, if no table is specified it means "all the tables for this databaseName". …

Add support for creating db intents to all the tables in a single database

---

src/operator/main.go
src/prometheus/metrics.go
src/shared/operatorconfig/config.go

Fixed problem where custom Prometheus metrics would not be exposed alongside the standard controller-runtime metrics.
Unrelated fix discovered while debugging: the webhook health/ready checker made it so starting the intents-operator locally requires the webhook server to start, even if webhooks are disabled. The health and ready checker now use the webhook server only if webhooks are not disabled.
Manually tested by querying the metrics endpoint.

Fixed problem where custom Prometheus metrics would not be exposed alongside the standard controller-runtime metrics

---

src/operator/main.go
src/shared/operatorconfig/config.go
src/shared/telemetries/errorreporter/errorrerporter.go
src/shared/telemetries/telemetriesconfig/config.go

Make errors API key a per-component configuration and update config to support non-helm installation.
This is a configuration check and can be tested manually
There is no documentation change required for this PR since it's aligned with existing statement on docs

Support error reporting default configuration on non-Helm installations

---

src/operator/main.go

Until this PR, initialization errors where logged as `logrus.Fatal` and were followed by a call to `os.Exit`. Since the bugsnag-logrus hook report errors asynchronously, in many cases the process was killed before the error was sent.
This PR turn all errors on init to panic exception, since the panic handler report the error synchronously.

Use panic for error on init

---

src/shared/otterizecloud/graphqlclient/generate.go
src/shared/otterizecloud/graphqlclient/schema.graphql
src/shared/telemetries/telemetriesgql/generated.go
src/shared/telemetries/telemetriesgql/schema.graphql
src/shared/telemetries/telemetrysender/global_sender.go

Get cloud client graphql schema using `https` instead of `http`
Run make generate and see the command succeeded schema is create as expected
No documentation is required for this change

Fix make generate - get cloud client graphql schema using TLS

---

README.md
src/operator/controllers/intents_controller.go
src/operator/controllers/intents_reconcilers/database/database.go
src/operator/controllers/intents_reconcilers/database/database_test.go
src/shared/operatorconfig/config.go

In this PR I enabled the new database reconciler which was experimental and disabled by default until now.

Enable database reconciler by defaults

---

src/operator/controllers/intents_controller.go
src/operator/main.go
src/shared/operatorconfig/config.go

Change the flag name so it's consistent with the other reconcilers flags.

Change `enableDatabaseReconciler` flag name to `enableDatabaseCredentialsCreation`

---

.github/workflows/release-tag.yaml

Previously, we would `docker tag` and `docker push`, which does not work with multiplatform. This now uses `docker buildx` to push.

Fix multiplatform release publish

---

src/operator/controllers/istiopolicy/policy_manager.go
src/operator/controllers/istiopolicy/policy_manager_test.go

Istio policy enforcement doesn't support k8s service intents (a.k.a. servers with prefix `svc:`) and should be ignored just like ingress network policy.

Fix bug: Operator generates Istio policy for service intents instead of ignoring

---

src/operator/controllers/intents_reconcilers/port_egress_network_policy/port_egress_network_policy.go
src/operator/controllers/intents_reconcilers/port_egress_network_policy/port_egress_network_policy_test.go
src/operator/controllers/intents_reconcilers/port_network_policy/port_network_policy.go
src/operator/controllers/intents_reconcilers/port_network_policy/port_network_policy_test.go

The operator doesn't support intents for services without pods, so intents to those services should result in error and should not generate intents

Fix bug: Generate policy with no pod selector for service without pod instead of returning error

---

.golangci.yaml
src/operator/api/v1alpha3/clientintents_types.go
src/operator/config/crd/k8s.otterize.com_clientintents.yaml
src/operator/controllers/aws_pod_reconciler/pods.go
src/operator/controllers/intents_controller.go
src/operator/controllers/intents_reconcilers/aws_reconciler.go
src/operator/controllers/intents_reconcilers/consts/consts.go
src/operator/otterizecrds/clientintents-customresourcedefinition.yaml
src/shared/awsagent/types.go
src/shared/reconcilergroup/reconcilergroup.go
src/shared/serviceidresolver/serviceidresolver.go

Added observedGeneration field to status field, so that it's now clear if the intent is truly up to date.
Fixed errors that would resolve upon retry, but did so in a noisy way when they just needed to be ignored or quietly retried.

Improve ClientIntents' status field accuracy for AWS intents, and add more Kubernetes Events to indicate success and failure cases

---

src/operator/api/v1alpha3/clientintents_types.go
src/operator/controllers/intents_controller.go
src/operator/controllers/intents_reconcilers/cloud_reconciler.go
src/operator/controllers/intents_reconcilers/port_egress_network_policy/port_egress_network_policy.go
src/operator/controllers/intents_reconcilers/port_egress_network_policy/port_egress_network_policy_test.go
src/operator/controllers/intents_reconcilers/port_network_policy/port_network_policy.go
src/operator/controllers/intents_reconcilers/port_network_policy/port_network_policy_test.go
src/shared/otterizecloud/graphqlclient/schema.graphql
src/shared/telemetries/telemetriesgql/schema.graphql

It's a common implementation to have the control plane API server service with no pod, just an endpoint mapped to a server outside of the cluster network. Since egress enforcement requires explicitly enabling access to the API server, this PR allow the user to declare intents to the service in the format: `svc:kubernetes.default`, and the result will be an egress network policy to the server IP address and port.
Egress network policy is an experimental feature, full documentation will be available on official release.

Support applying intents to API server "kubernetes" service, even when it doesn't have a pod

---

src/operator/config/rbac/role.yaml
src/shared/serviceidresolver/serviceidresolver.go

Until this PR if one chose to install Otterize with `--set global.allowGetAllResources` set to `false`,  Otterize failed to resolve the root owner of pods created by jobs and cronJobs. In this PR I added the relevant kubebuilder magic to the `serviceidresolver` package, and generated new clusterRoles.

Add RBAC read permissions of `batch/jobs` and `batch/cronjobs` for Otterize service id resolving

---

src/shared/telemetries/errorreporter/errorreporter.go

Error telemetry reporting would be incorrectly tagged as "staging".

Fix bug where error telemetry reporting would be incorrectly tagged in some cases

---

src/shared/awsagent/roles.go

Sets a "permission boundary" for AWS roles. Permission boundaries are an additional limit on IAM roles. They are used to ensure roles, created by credential-operator for example, do not have excessive permissions.
References:
https://github.com/otterize/intents-operator/pull/337

Set permission boundary for new AWS intents roles

---

src/operator/controllers/pod_reconcilers/pods.go

Prior to this PR, the intents operator would always label pods, even if network policies are not being managed by the intents operator.

Avoid labeling pods if network policy creation is disabled

---

src/operator/config/rbac/role.yaml
src/operator/controllers/validating_webhook_configurations_controller.go
src/operator/otterizecrds/ensure.go
src/shared/filters/filters.go
src/shared/filters/filters_test.go

Ensure the existence of `app.kubernetes.io/part-of=otterize` label on Otterize managed `CustomResourceDefinitions`.
https://github.com/otterize/intents-operator/pull/338

Fixed a case where already installed Otterize deployments stoped overwrite their conversion-webhooks certificates

---

.github/workflows/intents-spec.yaml
.github/workflows/netpol-e2e-test.yaml

Fix the operator CI/CD e2e to ignore the section of ClientIntents status.

Fix CI/CD e2e test to ignore the status part of the ClientIntents resource

---

src/operator/controllers/pod_reconcilers/pods.go

A previous PR intended to eliminate some cases where we label pods unnecessarily caused pods to not be labeled when Istio policies did in fact require labeling pods.

Fix bug where pods would not be labeled if network policies were disabled but Istio policies were enabled

---

src/operator/controllers/intents_controller.go
src/operator/controllers/kafkaserverconfig_controller.go
src/operator/controllers/pod_reconcilers/pods.go
src/shared/otterizecloud/otterizecloudclient/cloud_client.go
src/shared/telemetries/basicbatch/batcher.go
src/shared/telemetries/telemetrysender/sender.go

Prior to this PR, some errors would be reported without parameters or stack, or reported twice - once by being logged manually, and once because the error was returned. This PR corrects that.

Convert some remaining error logs into errors with stack traces to improve error reporting

---

.github/workflows/intents-spec.yaml
.github/workflows/netpol-e2e-test.yaml
.github/workflows/test-bashrc.sh

Removing the line who check the `spec` section of ClientIntents CRD since it's flaky.

Remove flaky CRD spec format testing from e2e test

---

src/shared/telemetries/errorreporter/errorreporter.go

This change prevents development versions and test versions from reporting telemetry errors.

Exclude test & development versions from reporting telemetry errors

---

src/operator/controllers/intents_reconcilers/kafka_acls_test.go

Due to limitations of TestENV platform, the reconciler is expected to have re-queue once in a while during tests. This is also a valid behavior in real-life since Kubernetes is an "eventual consistent" system. The ACL admin logs existing ACLs almost every time the reconciler is called. 
This cause few tests to be flaky. In the rare cases a re-queue is triggered, the call to logs isn't expected in `gomock` SDK and the test fail with no reason. So we should expect this call in any test expect those where the test flow should never reach the ACL log function.

Expect ACL logs when reconciler is re-queued

---

src/operator/controllers/intents_reconcilers/internet_network_policy/internet_network_policy.go
src/operator/controllers/intents_reconcilers/internet_network_policy/internet_network_policy_test.go

The network mapper update the ClientIntents status with IPv6 address from DNS addresses. The operator should create a CIDR only for the discovered address, with `/128` mask.

Fix bug when IPv6 address create /32 CIDR instead of /128

---

src/shared/awsagent/roles.go
src/shared/telemetries/errorreporter/errorreporter.go

Previously, the operator would always attempt to untag. This resulted in a no-op.

Improvement: untag AWS roles and policies only if configuration has changed

---

src/shared/azureagent/credentials.go

Rename create-azure-role-assignment label to create-azure-workload-identity for compatibility with other IAM providers

Rename create-azure-role-assignment label to create-azure-workload-identity for compatibility with other IAM providers

---

src/shared/azureagent/policies.go
src/shared/azureagent/policies_test.go

On Azure intents, allow providing partial scope name, omitting the subscription ID and resource group. 
The intents-operator will automatically detect partial scopes and expand them to include the subscription ID & resource group provided to the operator upon installation.

Auto-expand Azure intents scope with operator-provided subscription ID & resource group

---

src/operator/main.go
src/shared/operatorconfig/config.go

Bugfix: intents operator CLI flags parsing out of main scope breaks credentials-operator dependency
Introduced by this commit: https://github.com/otterize/intents-operator/commit/19b08b3e14b7bbdf4b5d1bbef9b95ab32ee7f7fb

Bugfix: intents operator CLI flags parsing out of main scope breaks credentials-operator dependency

---

src/operator/main.go

This PR adds reporting for the enforcement status for AWS IAM, PostgreSQL, GCP and Azure. This enforcement status is used to display the operator's state in Otterize Cloud, and to automatically display correct access status in the access graph.

Report enforcement status to Otterize Cloud for AWS IAM, PostgreSQL, GCP and Azure

---

src/go.mod
src/go.sum
src/operator/api/v1alpha3/clientintents_types.go
src/shared/azureagent/identities.go
src/shared/azureagent/policies.go

In intents of type Azure (and other non-k8s types), we should never try to split the server "name" to name & namespace. 
This bug breaks intents with Azure resource names such as `/providers/Microsoft.Storage/storageAccounts/otterizetutorialazureiam/blobServices/default/containers/test`, as the name is split around the period when reporting to Otterize cloud. 
Additionally, fixed a bug where if the intents operator attempts to handle a deleted `ClientIntents` resource whose workload identity no longer exists, it fails to reconcile it.

Bugfix: avoid splitting target server name on intents of type Azure (and other non-k8s types)

---

src/operator/controllers/intents_reconcilers/networkpolicy/builders/ingress_dns_server_allow_network_policy.go
src/operator/controllers/intents_reconcilers/networkpolicy/builders/ingress_dns_server_allow_network_policy_test.go
src/operator/controllers/intents_reconcilers/networkpolicy/reconciler.go
src/operator/main.go

Prior to this PR, Otterize would generate network policies that also affected UDP traffic. If a ClientIntent targeted coredns, then all other traffic to coredns would be blocked.

Improvement: Otterize network policies auto-allows DNS traffic if target is the cluster's DNS server and an Otterize network policy would block it

---

src/operator/controllers/intents_controller.go

When the event mapping function where first introduced into the operator, the interface didn't included context. This PR use the context provided instead of creating new one

Use runtime context on when mapping events instead of background context

---

src/shared/azureagent/identities.go

This PR fixes a bug in Otterize's credentials-operator, whereby when attempting to delete user assigned identities & federated identity credentials, the operator may hit an 404 (not found) error. This is part of the normal operator flow, and should not be reported as an error.

Bugfix: ignore error 404 NOT_FOUND on attempting to delete user assigned identities

---

src/operator/controllers/intents_reconcilers/networkpolicy/builders/builders_test.go
src/operator/controllers/intents_reconcilers/networkpolicy/builders/port_egress_network_policy.go
src/operator/controllers/intents_reconcilers/networkpolicy/builders/port_egress_network_policy_test.go
src/operator/controllers/intents_reconcilers/networkpolicy/builders/port_network_policy.go
src/operator/controllers/intents_reconcilers/networkpolicy/builders/port_network_policy_test.go
src/operator/controllers/intents_reconcilers/networkpolicy/builders/test_base.go

Fix a case where intents to services with a namedPort created network policies without port specification
Fix a case where intents to services with a namedPort created network policies without port specification

Fix a case where intents to services with a namedPort created network policies without port specification

---

src/operator/controllers/external_traffic/network_policy.go
src/operator/controllers/intents_reconcilers/external_traffic_network_policy/external_traffic_network_policy_test.go
src/shared/testbase/testsuitebase.go

To check if server is blocked by Otterize, the external network policy handler list all policies for that server, but with limit of 1. This was probably written before we hade default deny policies, and since those policies doesn't have ingress rule, the handler skipped the creation of this policy and deleted it in case it was created by another flow.
This PR also fix the problem that protected server who accepts external traffic but have no intents to it get blocked by the default deny network policy, even thought the graph will show this edge as green.

Fix bug where external access policy is not created for protected services with ingress

---

src/operator/controllers/intents_reconcilers/networkpolicy/reconciler.go
src/operator/effectivepolicy/groupreconciler.go
src/shared/logrus_bugsnag/logrus.go

When using Go standard library errors groups with Bugsnag API, the errors are reported as one error with the stack trace of call to `errors.Join` instead of the stack trace of the errors. This PR notify Bugsnag with each error, individually.
Due to the infrastructure nature of this change, it can be tested by running the code locally and tracking the errors reported

Report errors group one by one instead of all together

---

src/operator/controllers/intents_reconcilers/aws_reconciler.go
src/shared/awsagent/agent.go
src/shared/awsagent/policies.go
src/shared/awsagent/policies_test.go

This PR adds support for templating AWS resource names by AWS region and AWS account ID. 
The `$(AWS_REGION)` & `$(AWS_ACCOUNT_ID)` templates on AWS resource names will be automatically replaced by the EKS cluster's region & account ID. 
Usage:
```yaml
apiVersion: k8s.otterize.com/v1alpha3
kind: ClientIntents
metadata:
name: client
spec:
service:
name: client
calls:
- name: arn:aws:sqs:$(AWS_REGION):$(AWS_ACCOUNT_ID):queue1
type: aws
awsActions:
- "sqs:*"
```

Support templating by $(AWS_REGION) & $(AWS_ACCOUNT_ID)

---

src/operator/controllers/intents_controller.go
src/operator/controllers/intents_controller_test.go
src/operator/controllers/intents_reconcilers/external_traffic_network_policy/external_traffic_network_policy_test.go
src/operator/controllers/intents_reconcilers/external_traffic_network_policy/external_traffic_network_policy_with_no_intents_test.go
src/operator/controllers/intents_reconcilers/istio_policy.go
src/operator/controllers/intents_reconcilers/istio_policy_test.go
src/operator/controllers/intents_reconcilers/kafka_acls.go
src/operator/controllers/intents_reconcilers/kafka_acls_test.go
src/operator/controllers/intents_reconcilers/networkpolicy/builders/ingress_network_policy_test.go
src/operator/controllers/intents_reconcilers/networkpolicy/builders/test_base.go
src/operator/controllers/intents_reconcilers/networkpolicy/reconciler.go
src/operator/controllers/intents_reconcilers/protected_services/should_protect.go
src/operator/controllers/istiopolicy/policy_manager.go
src/operator/controllers/istiopolicy/policy_manager_test.go
src/operator/controllers/pod_reconcilers/pods.go
src/operator/controllers/pod_reconcilers/pods_test.go
src/operator/main.go
src/shared/operatorconfig/config.go

Until this PR, when one used shadowEnforcement mode, he could turn on enforcement only by using `protectedServices`, a per-service CRD. In this PR I'm adding support for per-namespace configuration using the helm chart. 
https://github.com/otterize/helm-charts/pull/194
https://github.com/otterize/docs/pull/225

Support enabling enforcement per namespace while using defaultShadow enforcement mode

---

src/operator/main.go
src/shared/logrus_bugsnag/logrus.go
src/shared/telemetries/errorreporter/errorreporter.go

Prior to this PR, the error sent would be a wrapped *logrus.Entry, resulting in hard-to-parse errors.

Fix issue where panics would be misreported in error telemetry

---

src/intents-operator.Dockerfile

Uses $BUILDPLATFORM in build stage in Dockerfile: This will cause the builder image to be arm64 on Macs, and amd64 on CI and other environments.
Not cross-compiling arm64->amd64 on macs is significantly faster. The resulting images are without change.
https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/

Use $BUILDPLATFORM in Dockerfile

---

src/shared/otterizecloud/otterizecloudclient/cloud_client.go
src/shared/telemetries/telemetrysender/sender.go

Prior to this PR, we inadvertently ignored the HTTP_PROXY, HTTPS_PROXY env variables in Otterize's cloud and telemetry HTTP clients. We now use the default transport.

Add support for HTTP_PROXY, HTTPS_PROXY env variables

---

src/shared/telemetries/errorreporter/errorreporter.go

Addressing empty version before determining release stage to avoid cases where locally built images with no version that happen to error, will get reported as production envs

Addressing empty version before determining release stage

---

src/operator/controllers/intents_reconcilers/networkpolicy/reconciler.go
src/operator/controllers/kafkaacls/servers_store.go
src/shared/azureagent/identities.go
src/shared/errors/errors.go
src/shared/serviceidresolver/serviceidresolver.go

When creating a new error using bugsnag constructor it will freeze the error traceback. instead we fallback to go default error module that does not apply a traceback and bugsnag will add the traceback on throw.

Fix error reporting for errors caused by sentinel errors

---

src/operator/main.go
src/shared/panichandler.go

Prior to this PR, panics were reported with the stack trace of the panic recover code in controller-runtime.

Add stack traces to panics reported in telemetry error reporting

---

src/operator/controllers/intents_reconcilers/database/database_reconciler.go

This PR fixes a bug in database integrations, where the intents-operator did not apply the `database-access` annotation if intents are applied before pod admission.

Bugfix on database integrations: pods were annotated with DB names when intents are applied before pod admission

---

src/operator/controllers/intents_reconcilers/networkpolicy/builders/dns_egress_network_policy.go
src/operator/controllers/intents_reconcilers/networkpolicy/builders/dns_egress_network_policy_test.go
src/operator/controllers/intents_reconcilers/networkpolicy/builders/egress_network_policy.go
src/operator/controllers/intents_reconcilers/networkpolicy/builders/egress_network_policy_test.go
src/operator/controllers/intents_reconcilers/networkpolicy/builders/port_egress_network_policy.go
src/operator/controllers/intents_reconcilers/networkpolicy/builders/port_egress_network_policy_test.go
src/operator/main.go
src/shared/operatorconfig/config.go

Fixed a bug where the DNS egress rules created by the operator would be added twice to each network policy.
Also enabled pprof for the operator by default, to enable performance profiling.

Fix bug where DNS egress rules would be added twice; enable pprof by default on loopback

---

src/operator/controllers/intents_reconcilers/database/database_reconciler.go
src/shared/databaseconfigurator/dbconfigurator.go

Added logic to clean database access annotation for deleted intents and update pod with 'access changed' timestamp for already existing instances
Also include details of the environment this PR was developed in …

Fixed bug where deleted & reapplied intents would not trigger credentials-operator to configure database password

---

src/operator/controllers/intents_reconcilers/database/database_reconciler_test.go
src/shared/clusterutils/username.go

Fixing a bug where hashed usernames would exceed allowed MySQL username length.
Added a UT in database reconciler tests to ensure long workload & namespace names do not exceed the maximum length.

Fixing bug where hashed usernames would exceed allowed MySQL username length

---

src/operator/controllers/external_traffic/network_policy.go

Catch and ignore k8s NotFound errors when attempting to delete and already non-exising network policy rule.

Ignore not-found errors when attempting to delete external traffic policies

---

src/operator/api/v1alpha2/intents_types.go

Fix 'missing annotation shared service account' error reported due to race in intents reconcilers, when the cloud reconciler is called on intents which haven't completed the policy reconciler loop just yet.

Fix 'missing annotation shared service account' error reported due to race in intents reconcilers

---

src/operator/api/v1alpha3/otterize_labels.go
src/shared/awsagent/rolesanywhere_creds/credentials_provider.go
src/shared/databaseconfigurator/postgres/postgres.go
src/shared/databaseconfigurator/postgres/utils.go
src/shared/gcpagent/utils.go

Replace usage of `fmt.Errorf` with our internal `errors.Errorf` implementation, to ensure that errors are reported with full stack traces.

Fix error reporting missing stack trace due to using fmt.Errorf rather than errors.Errorf

---

.github/workflows/lint.yml
.markdownlint.json
CODE_OF_CONDUCT.md
README.md
src/operator/README.md
src/operator/config/README.md

This PR adds the [markdown-lint GitHub action](https://github.com/marketplace/actions/markdown-lint), checking for markdown issues in MD files, and a step for running `go vet` as part of the go lint action. 
Additionally, this fixes any existing markdown issues. 
- https://github.com/marketplace/actions/markdown-lint

Add Markdown linter &  go vet GitHub actions and fix lint issues detected by it

---

src/operator/api/v2alpha1/clientintents_types.go
src/operator/controllers/intents_reconcilers/cloud_reconciler_test.go

Since the last merge, applied intents with Kafka intents were reported to the cloud without the target namespace. 
Added test for this use case.

Fix a case where applied kafka intents were reported without namespace to the cloud

---

src/operator/api/v2alpha1/clientintents_types.go
src/operator/controllers/intents_reconcilers/cloud_reconciler_test.go

Fix a bug where applied intents to Kubernetes API service couldn't be reported to the cloud properly.

Fix a bug where applied intents to the Kubernets API service couldn't be reported to the cloud properly

---

src/operator/controllers/intents_reconcilers/pods.go

Avoid overriding containers list on pod when patching label using strategic merge instead of regular (overriding) merge

Avoid overriding containers list on pod when patching label

---

src/operator/api/v1alpha3/clientintents_types.go
src/operator/api/v1alpha3/webhooks.go
src/operator/api/v1alpha3/webhooks_test.go
src/operator/api/v1beta1/webhooks.go
src/operator/api/v1beta1/webhooks_test.go

The webhook didn't convert `clientIntents.Status` and caused an infinite reconciliation loop of the intents-controller.

Fix a case of an infinite reconciliation loop caused by a missing status of converted `clientIntents`

---

src/operator/controllers/custom_resource_definition_controller.go
src/operator/controllers/custom_resource_definition_controller_test.go
src/operator/controllers/intents_reconcilers/client_matcher.go
src/operator/controllers/validating_webhook_configurations_controller.go
src/operator/controllers/validating_webhook_configurations_controller_test.go

Make sure the webhook reconciler patches the latest `CRD`/`validationWebhook` version - to reduce the risk of wrong CA bundle edge cases

Ensure webhook reconciler patches the Latest `CRD`/`ValidationWebhook` revision to minimize CA bundle edge cases

---

src/operator/controllers/intents_reconcilers/client_matcher.go
src/operator/controllers/intents_reconcilers/database/database_reconciler.go
src/operator/controllers/intents_reconcilers/pods.go
src/operator/controllers/intents_reconcilers/pods_test.go
src/operator/controllers/pod_reconcilers/namespace.go
src/operator/controllers/pod_reconcilers/namespace_test.go
src/operator/controllers/pod_reconcilers/pods.go
src/shared/gcpagent/config_conector.go

This PR fixes a bug in the operator, in which updating pod labels and annotations sometimes failed due to unexpected changes being detected in the pod's containers. 
This is resolved by using StrategicMergeFrom rather than (plain) MergeFrom, which applies updates as strategic patches rather than complete overrides. 

Avoid attempting to override pod containers when updating labels & annotations

---

src/shared/operator_cloud_client/status_report.go

Report the configuration to the cloud on init, in addition to the periodic report task

Fix a bug where it took 10 minutes to sync operator's configuration with the cloud

---

src/operator/config/webhook/manifests-patched
src/operator/config/webhook/manifests.yaml
src/operator/webhooks/mysqlserverconfigs_webhook_v1.go
src/operator/webhooks/postgresqlserverconfigs_webhook_v1.go
src/operator/webhooks/protectedservices_webhook_v1.go

The validation webhook should use the explicit name of the version. Otherwise it won't work.

Fix validation webhook paths for api version `v1beta1`

---

src/operator/api/v1alpha3/webhooks.go
src/operator/api/v1alpha3/webhooks_test.go
src/operator/api/v1beta1/webhooks.go
src/operator/api/v1beta1/webhooks_test.go

Fix a bug where using clientIntents conversion webhook from `v2` to `v1` could crash if it has `service` target to `kubernetes.default`

Fix a bug where using clientIntents conversion webhook from `v2` to `v1` could crash if it has `service` target to `kubernetes.default`

---

src/operator/controllers/external_traffic/network_policy.go
src/operator/controllers/external_traffic/network_policy_test.go
src/operator/controllers/external_traffic/service_uploader.go
src/operator/controllers/external_traffic/service_uploader_test.go
src/operator/controllers/external_traffic/shared.go
src/operator/controllers/intents_reconcilers/external_traffic_network_policy/external_traffic_network_policy_test.go
src/operator/controllers/intents_reconcilers/external_traffic_network_policy/external_traffic_network_policy_with_ingress_controllers_configured_test.go
src/operator/controllers/intents_reconcilers/external_traffic_network_policy/external_traffic_network_policy_with_no_intents_test.go
src/operator/main.go
src/shared/operatorconfig/config.go
src/shared/otterizecloud/graphqlclient/generate.go
src/shared/otterizecloud/graphqlclient/generated.go
src/shared/otterizecloud/graphqlclient/schema.graphql
src/shared/telemetries/telemetriesgql/schema.graphql

Enable with `--set operator.ingressControllerAWSALBExempt=true`. Use `intentsOperator.operator.ingressControllerAWSALBExempt` if using the `otterize-kubernetes` Helm chart.
Prior to this PR, if the `ingressControllers` configuration was passed in order to restrict Ingress traffic to in-cluster ingress Pods, AWS ALB would be (correctly) blocked. This PR enables the intents operator to detect when an AWS ALB ingress resource is used in tandem, and to open access to that pod as required.

Add support for detecting AWS ALB ingress resources and auto-allowing traffic

---

src/shared/operator_cloud_client/status_report.go
src/shared/otterizecloud/graphqlclient/generated.go
src/shared/otterizecloud/graphqlclient/schema.graphql

The previous, as of yet unreleased PR #476 did not upload the configuration to Otterize Cloud that is necessary for correctly calculating the access status.

Upload AWS ALB exemption config to cloud

---

src/operator/controllers/external_traffic/network_policy.go
src/operator/controllers/external_traffic/service_uploader.go
src/operator/controllers/external_traffic/shared.go
src/operator/controllers/intents_reconcilers/external_traffic_network_policy/external_traffic_network_policy_with_ingress_controllers_configured_test.go

This was done because `target-type`: `ip` is sufficient to indicate that an AWS ALB will attempt to connect, rather than `scheme`: `internet-facing`.

Use `"alb.ingress.kubernetes.io/target-type"` instead of `"alb.ingress.kubernetes.io/scheme"` to detect AWS ALB presence on Ingress

---

src/operator/controllers/istiopolicy/policy_manager.go

During upgrades, two operators could attempt to create the same Istio policy, and then one would fail. This should not be reported as an error.

Fix bug where Istio policy would incorrectly report an error before retrying and succeeding

---

src/shared/operator_cloud_client/status_report.go
src/shared/otterizecloud/graphqlclient/generated.go
src/shared/otterizecloud/graphqlclient/schema.graphql

Report `AllowExternalTrafficPolicy` to the cloud to improve access status calculation for non-default config
https://docs.otterize.com/reference/configuration/intents-operator/helm-chart

Report `AllowExternalTrafficPolicy` to the cloud to improve access status calculation for non-default config

---

src/shared/awsagent/errorhandling.go
src/shared/awsagent/policies.go
src/shared/awsagent/roles.go
src/shared/azureagent/identities.go
src/shared/gcpagent/config_conector.go

This PR fixes a few bugs in the AWS I AM integration managing of IAM policies:
- Attempt to delete an already deleted IAM policy would raise a NoSuchEntity error (which should be ignored)
- Attempt to create an already created IAM policy would raise an EntityAlreadyExists error (which should also be ignored). 
In addition, this PR adds some logging to IAM role deletion for easier troubleshooting. 
Also include details of the …

Bugfixes to AWS IAM policy creation and deletion edge cases

---

src/shared/operator_cloud_client/cloud_api.go
src/shared/operator_cloud_client/intent_events_sender.go
src/shared/otterizecloud/graphqlclient/generated.go
src/shared/otterizecloud/mocks/mock_cloud_api.go
src/shared/telemetries/telemetriesgql/generated.go
src/shared/telemetries/telemetriesgql/schema.graphql

This PR improves the robustness of reporting ClientIntent status & events, by adding two improvements: 
- Cache events & status only after successfully reporting them to Otterize Cloud, so that in case of reporting errors, the reporting will be retried on the next reporting interval. 
- Use an expirable LRU cache, with an expiry of 1 hour. This way even in case the Cloud somehow missed the report, it will be retried in 1 hour (assuming the status & events will still be there). 
Please include any manual steps for testing end-to-end or …

Improve ClientIntent status & event reporting robustness by using LRU cache & caching only after successful report

---

src/shared/operator_cloud_client/intent_events_sender.go

This PR fixes a faulty error report on the ClientIntent event reporting loop: when querying for intents associated with the event, we can simply ignore intents that have already been deleted, rather than reporting the NotFound error.

Bugfix in ClientIntent events reporting: mute NotFound errors on querying IntentEvents for ClientIntents that were already deleted

---

src/operator/controllers/external_traffic/network_policy.go
src/operator/controllers/intents_reconcilers/external_traffic_network_policy/external_traffic_network_policy_with_no_intents_test.go
src/operator/main.go
src/shared/operator_cloud_client/status_report.go
src/shared/operatorconfig/config.go
src/shared/operatorconfig/enforcement/config.go

Fix bug where "external allow" policies were created when the enforcement was disabled and "AllowExternalTraffic" was set to "Always"

Fix bug where "external allow" policies were created if "AllowExternalTraffic" was set to "Always" even though the enforcement was disabled

---

src/shared/databaseconfigurator/postgres/postgres.go

This PR changes a bug in the PostgreSQL integration, where non-existing PG users should be ignored when attempting to alter their passwords. 

Bugfix: fix wrong handling of non-existing PostgreSQL users when attempting to alter their passwords

---

src/operator/controllers/custom_resource_definition_controller.go
src/operator/controllers/intents_reconcilers/istio_policy.go
src/operator/controllers/intents_reconcilers/pods.go
src/shared/gcpagent/config_conector.go
src/shared/reconcilergroup/reconcilergroup.go

This PR fixes an issue with handling Kubernetes API 'Forbidden' errors during update, which are being wrongly reported as errors in the logs and on the Kubernetes resource. These errors are expected during the normal workflow of a reconciler, e.g. when the resource in question is already being deleted. They should be caught and the flow should be requeued (similar to 'Conflict' errors). 
Also include details of the environment this PR …

Fix Kubernetes API 'Forbidden' errors during update, being wrongly reported as errors on the resource

---

src/operator/controllers/external_traffic/network_policy.go

This PR fixes a wrongly reported NotFound error that occurs when the intents-operator attempts to delete an already deleted network policy.

Bugfix on external policy reconciler: catch NotFound errors when attempting to delete a network policy

---

src/shared/operator_cloud_client/intent_events_sender.go

This PR fixes an error that may be reported from intent-operators running on large environments, which may have a lot of ClientIntent objects & events. The internal cache for ClientIntent events may take a longer time to sync on startup. 

Bugfix: increase ClientIntent events cache first sync time limit to 60 seconds to prevent errors on large environments

---

src/shared/awsagent/roles.go

This PR fixes a bug in the AWS IAM roles anywhere integration, where the next token is unused when listing more than 2 pages of IAM profiles. 

Bugfix in AWS IAM roles anywhere integration: nextToken is not used when listing AWS IAM roles anywhere profiles

---

src/operator/api/v2alpha1/clientintents_types.go
src/operator/controllers/intents_controller.go
src/operator/controllers/intents_reconcilers/networkpolicy/builders/builders_test.go
src/operator/controllers/intents_reconcilers/networkpolicy/builders/dns_egress_network_policy.go
src/operator/controllers/intents_reconcilers/networkpolicy/builders/egress_network_policy.go
src/operator/controllers/intents_reconcilers/networkpolicy/builders/egress_network_policy_test.go
src/operator/controllers/intents_reconcilers/networkpolicy/builders/internet_network_policy.go
src/operator/controllers/intents_reconcilers/networkpolicy/builders/internet_network_policy_test.go
src/operator/controllers/intents_reconcilers/networkpolicy/builders/test_base.go
src/operator/effectivepolicy/groupreconciler.go
src/operator/effectivepolicy/types.go
src/shared/operator_cloud_client/intent_events_sender.go
src/shared/serviceidresolver/serviceidentity/serviceidentity.go

This works around an issue with the AWS VPC CNI where it does not allow traffic to the ClusterIP of a Service unless the NetworkPolicy uses the exact selector used by the Service.
Also fixes an unrelated issue where DNS traffic was not automatically allowed if the only targets were Internet intents.
This Pod has two sets of labels:
```
❯ kubectl get pods -n otterize-tutorial-iam -l intents.otterize.com/service=server-otterize-tutorial-ia-68873b
NAME                      READY   STATUS    RESTARTS   AGE
server-6dbbc4666f-nncjf   1/1     Running   0          85m
❯ kubectl get pods -n otterize-tutorial-iam -l app=server
NAME                      READY   STATUS    RESTARTS   AGE
server-6dbbc4666f-nncjf   1/1     Running   0          85m
```
app=server is the one used by the Service.
This …

Workaround AWS VPC CNI egress network policy agent bug: only allows traffic to ClusterIP if exact service selector is specified

---

src/operator/controllers/external_traffic/network_policy_reconciler.go
src/operator/controllers/intents_reconcilers/mocks/mock_external_netpol_handler.go
src/operator/controllers/intents_reconcilers/networkpolicy/builders/test_base.go
src/operator/controllers/intents_reconcilers/networkpolicy/reconciler.go
src/operator/main.go
src/shared/operator_cloud_client/cloud_api.go

This situation probably happened due to a race when two operators were running. I fixed it by:
1. Calling `externalPolicyHandler.HandleAllPods` for every run of the effective policy reconciler.
2. Add a netpol reconciler that triggers `externalPolicyHandler.HandlePodsInNamespace`

Fix a rare bug where external network policies were not deleted due to a race condition when the enforcement was turned off

---

src/operator/controllers/external_traffic/network_policy_reconciler.go

Change the logging level of "Handling external for namespace" from `info` to `debug`.

Change the logging level of "Handling external for namespace" from `info` to `debug`

---

src/operator/controllers/pod_reconcilers/pods.go

Changed `MergeFrom` to `StrategicMergeFrom` when patching pod labels to try and fix forbidden fields error on pod patching

Changed MergeFrom to StrategicMergeFrom when patching pod labels to try and fix forbidden fields error on pod patching

---

src/operator/controllers/external_traffic/network_policy_reconciler.go
src/operator/controllers/intents_reconcilers/istio_policy.go
src/operator/controllers/istiopolicy/policy_manager.go
src/shared/reconcilergroup/reconcilergroup.go

Catch "already exists" error to avoid unnecessary error events

Catch "already exists" error to avoid unnecessary error events

---

src/operator/controllers/intents_reconcilers/networkpolicy/builders/builders_test.go
src/operator/controllers/intents_reconcilers/networkpolicy/builders/dns_egress_network_policy_test.go
src/operator/controllers/intents_reconcilers/networkpolicy/builders/egress_network_policy_test.go
src/operator/controllers/intents_reconcilers/networkpolicy/builders/ingress_dns_server_allow_network_policy_test.go
src/operator/controllers/intents_reconcilers/networkpolicy/builders/ingress_network_policy_test.go
src/operator/controllers/intents_reconcilers/networkpolicy/builders/internet_network_policy_test.go
src/operator/controllers/intents_reconcilers/networkpolicy/builders/port_egress_network_policy_test.go
src/operator/controllers/intents_reconcilers/networkpolicy/builders/port_network_policy_test.go
src/operator/controllers/intents_reconcilers/networkpolicy/reconciler.go
src/shared/reconcilergroup/reconcilergroup.go

Incorrect use of `reflect.deepEqual` function caused false-updates of network policies and spam events.

Fix bug where network policies were patched even though the change was a no-op

---

src/operator/controllers/intents_controller.go
src/operator/health/reconciletime.go
src/operator/main.go

Prior to this PR, slow reconcile performance due to limited CPU or due to IO (slow network, slow responses from the control plane) could cause the operator to function slowly. If this is slow enough, then the operator is essentially not functioning properly -- if it can't reconcile in a timely manner, in practice it's not reconciling successfully, even if ultimately it does succeed.
The operator will now fail its health check if a reconcile starts and does not complete within 30 seconds, which will cause it to restart and perhaps self-heal the issue, but also indicate to the cluster operators that something is wrong and needs to be investigated, long before the issue materializes some other way.

Fail health check if intents reconcile starts and doesn't finish within 30s

---

src/operator/health/reconciletime.go

Increase health check timeout to 90 seconds - should be greater than internal timeouts in #508

Increase health check timeout to 90 seconds - should be greater than internal timeouts in #508

---

src/operator/controllers/external_traffic/network_policy.go
src/operator/controllers/intents_reconcilers/istio_policy.go
src/operator/controllers/intents_reconcilers/networkpolicy/reconciler.go
src/operator/controllers/intents_reconcilers/pods.go
src/shared/reconcilergroup/reconcilergroup.go
src/shared/reconcilergroup/reconcilergroup_test.go

This PR is a follow-up on a previous fix, made in https://github.com/otterize/intents-operator/pull/502. 
In some cases, where the inspected error was not wrapped using `errors.Wrap`, the code in the previous PR was wrongly Unwrapping it, causing the intents-operator missing common cases such as namespace not exist when creating network policies, and reporting them as errors. 
This is resolved by using `errors.As` rather than `errors.Unwrap`. 
https://github.com/otterize/intents-operator/pull/502
Please include any manual steps for testing …

Fix wrong handling of k8s errors causing wrong handling of applying netpols on non-existing namespaces

---

src/go.mod
src/operator/controllers/intents_reconcilers/networkpolicy/builders/internet_network_policy.go
src/operator/controllers/intents_reconcilers/networkpolicy/builders/internet_network_policy_test.go
src/shared/operatorconfig/config.go

ClientIntents with DNS names are eventually translated into Egress network policies with IP addresses. The number of IPs per policy could get quite big, causing unexpected behavior in multiple CNIs. This change adds a feature flag for consolidating IPs to `/24` networks to reduce the number of addresses per policy.

Support grouping internet network policies by /24 CIDR to reduce number of IP addresses per policy

---

src/operator/controllers/intents_reconcilers/networkpolicy/reconciler.go
src/operator/controllers/istiopolicy/policy_manager.go
src/operator/controllers/protected_service_reconcilers/default_deny.go
src/shared/serviceidresolver/serviceidentity/serviceidentity.go

Network policy names are based on the ServiceIdentity name they are created from. The service identity name might contain underscores, which are invalid characters for k8s objects (which must be valid DNS names according to RFC1123). Instead, use a name with the underscores replaced. The implementation of ServiceIdentity is not changed since that might have far-reaching effects in the system.
- Fixes https://github.com/otterize/network-mapper/issues/247

Use safe RFC1123 for network policy names

---

src/shared/awsagent/rolesanywhere_creds/credentials_provider.go

This fixes a bug in AWS IAM Roles Anywhere, caused due to a regression in AWS API. 
Prior to this fix, an empty `X-Amz-X509-Chain` header was added to AWS Roles Anywhere `CreateSession` request. This recently started failing the request, due to a change in the AWS API. 
This happens when the slice of intermediate CAs is empty. However, by passing a `nil` slice into the AWS roles anywhere signing helper, we make it avoid adding the empty header, which solves the issue. 
- Relevant line in rolesanywhere aws_signing_helper: https://github.com/aws/rolesanywhere-credential-helper/blob/v1.0.3/aws_signing_helper/signer.go#L213
Describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be …

Bugfix: solve "Invalid signature" error on AWS IAM Roles Anywhere

---

src/operator/controllers/intents_reconcilers/iam/iampolicyagents/azurepolicyagent/agent_identities_test.go
src/shared/azureagent/customroles.go
src/shared/azureagent/identities.go
src/shared/azureagent/roleassignments.go

Handle cases where there are hanging custom roles and assignments after deleting intents and kubernetes service accounts

Handle azure iam hanging resources

---

src/shared/azureagent/identities.go

The error type returned by "FindUserAssignedIdentity" is swapped from azure error to a sentinel error. align the calling function error checking to the sentinel error.

Align error type check when deleting a user assigned identity

---

src/shared/telemetries/errorreporter/errorreporter.go
src/shared/telemetries/errorreporter/errorsender.go
src/shared/telemetries/errorreporter/global_sender.go

Pass version string in shared code instead of loading from the file system - this fails on other applications that don't have the same file structure.

Pass version down to error reporter code

---

src/operator/controllers/intents_reconcilers/iam/iampolicyagents/azurepolicyagent/agent.go
src/operator/controllers/intents_reconcilers/iam/iampolicyagents/azurepolicyagent/agent_customroles_test.go
src/operator/controllers/intents_reconcilers/iam/iampolicyagents/azurepolicyagent/agent_identities_test.go
src/operator/controllers/intents_reconcilers/iam/iampolicyagents/azurepolicyagent/agent_keyvault_test.go
src/shared/azureagent/agent.go
src/shared/azureagent/azureclients.go
src/shared/azureagent/customroles.go
src/shared/azureagent/identities.go
src/shared/azureagent/mocks/azureclients.go
src/shared/azureagent/roleassignments.go
src/shared/azureagent/subscriptions.go
src/shared/otterizecloud/graphqlclient/schema.graphql
src/shared/telemetries/telemetriesgql/schema.graphql

Added support for cross-subscription access in Azure. A custom role with the relevant actions and data actions will be created in the resources subscription -> a new assignment will be created on the Kubernetes service managed identity pointing to that specific custom role.

Add support for Azure cross-subscription access

---

src/operator/controllers/custom_resource_definition_controller.go

Prevent nil pointer access in otterize crds
Bugsnag: runtime error: invalid memory address or nil pointer dereference

Prevent nil pointer access in otterize crds

---

src/operator/controllers/intents_reconcilers/networkpolicy/builders/dns_egress_network_policy.go
src/operator/controllers/intents_reconcilers/networkpolicy/builders/dns_egress_network_policy_test.go
src/operator/controllers/intents_reconcilers/networkpolicy/builders/ingress_dns_server_allow_network_policy.go
src/operator/controllers/intents_reconcilers/networkpolicy/builders/ingress_dns_server_allow_network_policy_test.go

Up until this PR if the kubernetes DNS server was mentioned in a `clientIntents` resource as a target, we added to its network policy an "allow all UDP port 53 rule", in this PR we added an "allow all TCP port 53" rule so it will auto allow TCP DNS.
changed existing tests.

Allow TCP port 53 when creating an allow all NetworkPolicy to kube-dns - to support TCP DNS

---

src/operator/controllers/intents_reconcilers/networkpolicy/builders/test_base.go
src/operator/effectivepolicy/groupreconciler.go
src/operator/effectivepolicy/types.go

When building serviceEffectivePolicies - `populateReferencedKubernetesServices` logic is the heaviest part regarding CPU consumption. This logic is relevant only for egress policies (to work around AWS CNI limitation). Therefore, in this PR we changed it so it will only run if egress is enabled.

Improve CPU consumption by skipping `populateReferencedKubernetesServices` logic when egress enforcement is disabled

---

src/operator/config/rbac/manifests-patched.yaml
src/operator/config/rbac/role.yaml
src/operator/controllers/linkerd/linkerd_manager.go

Align permissions with those installed by the helm chart
https://github.com/otterize/helm-charts/blob/main/intents-operator/templates/intents-operator-manager-clusterrole.yaml

Align linkerd RBAC permissions for the intents-operator cluster role with the helm-chart

---

.github/workflows/netpol-e2e-test.yaml
src/operator/controllers/intents_reconcilers/cloud_reconciler.go

Until this PR we were overriding Service targets with the name of the workload. Since the cloud fully supports services access this override mechanism is not necessary anymore.

Support reporting applied ClientIntents targeting Kubernetes services to the cloud

---

src/go.mod
src/go.sum
src/operator/controllers/intents_reconcilers/iam/iampolicyagents/azurepolicyagent/agent.go
src/operator/controllers/intents_reconcilers/iam/iampolicyagents/azurepolicyagent/agent_customroles_test.go
src/operator/controllers/intents_reconcilers/iam/iampolicyagents/azurepolicyagent/agent_identities_test.go
src/operator/controllers/intents_reconcilers/iam/iampolicyagents/azurepolicyagent/agent_keyvault_test.go
src/operator/controllers/intents_reconcilers/iam/iampolicyagents/azurepolicyagent/agent_scope_test.go
src/shared/azureagent/agent.go
src/shared/azureagent/azureclients.go
src/shared/azureagent/mocks/azureclients.go
src/shared/azureagent/resources.go
src/shared/otterizecloud/graphqlclient/generated.go
src/shared/otterizecloud/graphqlclient/schema.graphql
src/shared/telemetries/telemetriesgql/generated.go
src/shared/telemetries/telemetriesgql/schema.graphql

This PR fixes an error which occured when applying Azure ClientIntents on KeyVault scopes, such as this: 
```
apiVersion: k8s.otterize.com/v2alpha1
kind: ClientIntents
metadata:
name: client-intents-for-client
namespace: otterize-tutorial-azure-iam
spec:
workload:
name: client
kind: Deployment
targets:
- azure:
scope: /subscriptions/SUBSCRIPTION/resourceGroups/RESOURCEGROUP/providers/Microsoft.KeyVault/vaults/VAULTNAME
roles: 
- Key Vault Secrets User
```
This resulted in the following API error when attempting to reconcile the intents:
```
{                                                                                                                                                                                                                                                
"error": { …
```

Fix Azure API version error when applying Azure ClientIntents on KeyVault scopes, by querying for supported API versions by resource type

---

src/operator/controllers/intents_reconcilers/linkerd_reconciler.go

Fixed possible panic caused by calling wrong event recorder when handling effective policy for Linkerd

Fixed possible panic caused by calling wrong event recorder when handling effective policy for Linkerd

---

src/operator/controllers/intents_reconcilers/iam/iampolicyagents/awspolicyagent/multi_account_aws_policy_agent.go
src/shared/awsagent/agent.go
src/shared/awsagent/multi_account_aws_agent/account_getters.go

This PR fixes an issue with the AWS IAM integration, where pods labeled with `credentials-operator.otterize.com/create-aws-role` were assigned an Otterize-generated IAM role, ignoring the label value. Meaning that if a pod was labeled with `credentials-operator.otterize.com/create-aws-role=false`, the integration would still create and assign an IAM role for it, possibly overriding any other user-managed role assigned to it. 
https://github.com/otterize/credentials-operator/pull/178
https://github.com/otterize/intents-operator/pull/549
Please …

Fix bug where AWS IAM roles could be created for a particular workload even when disabled for that particular workload

---

src/operator/controllers/intents_reconcilers/iam/iam_reconciler.go
src/operator/controllers/intents_reconcilers/iam/iam_reconciler_test.go
src/shared/agentutils/agentutils.go
src/shared/awsagent/policies.go

In cases when AWS roles were already deleted (possibly by the credentials operator) in a race condition, re-queue the event for another attempt.

Solve a potential race on AWS IAM integration where policy deletion would error because the related IAM role was not found

---

src/operator/controllers/intents_reconcilers/iam/iampolicyagents/azurepolicyagent/agent.go
src/operator/controllers/intents_reconcilers/iam/iampolicyagents/azurepolicyagent/agent_customroles_test.go
src/operator/controllers/intents_reconcilers/iam/iampolicyagents/azurepolicyagent/agent_identities_test.go
src/operator/controllers/intents_reconcilers/iam/iampolicyagents/azurepolicyagent/agent_periodic_test.go
src/operator/controllers/intents_reconcilers/iam/iampolicyagents/azurepolicyagent/periodic.go
src/operator/main.go
src/shared/azureagent/agent.go
src/shared/azureagent/customroles.go
src/shared/azureagent/identities.go
src/shared/azureagent/periodic.go
src/shared/azureagent/roleassignments.go
src/shared/otterizecloud/graphqlclient/generated.go
src/shared/otterizecloud/graphqlclient/schema.graphql
src/shared/telemetries/telemetriesgql/generated.go
src/shared/telemetries/telemetriesgql/schema.graphql

Periodically Check and cleanup orphaned resources in azure that could have been left over because of network errors or race conditions. Some resources (such as custom roles and role assignments) must be deleted together and an interrupt in the middle of the deletion transaction might cause orphaned resources.

Periodically Check and cleanup orphaned resources in azure

---

src/operator/main.go
src/shared/operator_cloud_client/status_report.go
src/shared/otterizecloud/otterizecloudclient/config.go

The operator could fail to query Linkerd/Istio status because the cache is not yet initialized. This would result in reporting a "true" value, which the cloud would use to calculate the access graph and in turn result in incorrect access statuses.
Fixed the issue where the cache was not initialized by adding a wait, and also no longer assume "true" for installation on failure.

Fix bug where operator config report would report incorrect Istio/Linkerd installation status upon startup

---

src/operator/main.go

Fix STARTED telemetry sent by the intents-operator, to be sent with `count=1` (rather than 0), making it consistent with other OSS components.

Fix intents-operator sending STARTED telemetry with 0-count, which is inconsistent with other operators

---

src/shared/operatorconfig/enforcement/config.go

Fixing setting the initial value of `AllowExternalTraffic` configuration when there is no value in the helm file.
Technical details:
When creating the configuration, we are fetching this value using `viper.GetString()`, which expect a string value (rather than enum), so we must set it as string as well.
Tested locally by running the intents operator and making sure that it reports values to Otterize cloud..

Resolve an issue where the AllowExternalTraffic configuration was not set to its default value

---

src/operator/config/rbac/manifests-patched.yaml
src/operator/config/rbac/role.yaml
src/operator/main.go
src/operator/webhooks/certs.go

Before this PR, the intents operator would recreate its webhook TLS certificate upon startup. During rollout, this meant that the old and new instances of the operator would "fight" to keep their certificate the one that is configured on the cluster. This would resolve itself after a short while, as the old instance went down. However, it resulted in many errors in the log, and in rare cases, a startup time of over 200 seconds and multiple restarts until the operator was finally healthy.
This PR makes the operator reuse the certificate, so both the old and new instances will use the same one. Importantly, this means that the new operator can start WATCHing resources immediately. Before, if the new operator switched the webhook certificate, it could not watch ClientIntents, since …

Added support for reusing the webhook TLS certificate across different deployments to prevent cases where operator takes too long to start up

---

src/operator/main.go
src/operator/webhooks/certs.go
src/shared/operatorconfig/config.go

Refactor Persist/Read cert from secret functions so they will get the secret name as an argument to reuse them in the credentials-operator
https://github.com/otterize/intents-operator/pull/560

Refactor Persist/Read cert from secret functions so they can be reused by the credentials-operator to persist/read its certs

---

src/go.sum
src/operator/main.go
src/shared/operatorconfig/config.go

Fix issue in webhook cert persistency using secrets, where the credentials-operator secret name was wrong due to use of configuration. Instead, use fixed secret names.

Fix issue in webhook cert persistency where credentials-operator secret name was wrong due to use of configuration

---

src/operator/api/v1beta1/clientintents_types.go
src/operator/api/v1beta1/kafkaserverconfig_types.go
src/operator/api/v1beta1/mysqlserverconfig_types.go
src/operator/api/v1beta1/postgresqlserverconfig_types.go
src/operator/api/v1beta1/protectedservice_types.go
src/operator/api/v2alpha1/clientintents_types.go
src/operator/api/v2alpha1/kafkaserverconfig_types.go
src/operator/api/v2alpha1/mysqlserverconfig_types.go
src/operator/api/v2alpha1/postgresqlserverconfig_types.go
src/operator/api/v2alpha1/protectedservice_types.go
src/operator/config/crd/k8s.otterize.com_clientintents.patched
src/operator/config/crd/k8s.otterize.com_clientintents.yaml
src/operator/config/crd/k8s.otterize.com_kafkaserverconfigs.patched
src/operator/config/crd/k8s.otterize.com_kafkaserverconfigs.yaml
src/operator/config/crd/k8s.otterize.com_mysqlserverconfigs.patched
src/operator/config/crd/k8s.otterize.com_mysqlserverconfigs.yaml
src/operator/config/crd/k8s.otterize.com_postgresqlserverconfigs.patched
src/operator/config/crd/k8s.otterize.com_postgresqlserverconfigs.yaml
src/operator/config/crd/k8s.otterize.com_protectedservices.patched
src/operator/config/crd/k8s.otterize.com_protectedservices.yaml
src/operator/controllers/intents_reconcilers/mocks/mock_linkerd.go
src/operator/otterizecrds/clientintents-customresourcedefinition.yaml
src/operator/otterizecrds/kafkaserverconfigs-customresourcedefinition.yaml
src/operator/otterizecrds/mysqlserverconfigs-customresourcedefinition.yaml
src/operator/otterizecrds/postgresqlserverconfigs-customresourcedefinition.yaml
src/operator/otterizecrds/protectedservices-customresourcedefinition.yaml
src/shared/otterizecloud/graphqlclient/generated.go
src/shared/otterizecloud/graphqlclient/schema.graphql
src/shared/telemetries/telemetriesgql/generated.go
src/shared/telemetries/telemetriesgql/schema.graphql

Update the CRD storage version from `v1beta1` to `v2alpha1`. 
This change was made by:
1. Moved the "kubebuilder:storageversion" annotations from v1 structs to the v2
2. Ran `make manifests generate copy-manifests-to-helm`

Update the CRD storage version from `v1beta1` to `v2alpha1`

---

src/operator/controllers/linkerd/linkerd_manager.go

Fix a string formatting issue that caused ShouldNotCreatePolicy warning events text missing server name and namespace. 
https://github.com/otterize/intents-operator/issues/571

Fix ShouldNotCreatePolicy warning events text missing server name and namespace

---

src/shared/serviceidresolver/podownerresolver/podownerresolver.go
src/shared/serviceidresolver/serviceidresolver_test.go

In some cases, the object's owner reference may be incorrect or not included in the schema. We don't want to fail in those situations; it is sufficient to halt owner resolution and report the error. 

Fix bug where the workload identity resolution algorithm could fail if an owner ref uses a wrong apiVersion or kind

---

src/operator/api/v1alpha2/intents_types.go
src/operator/api/v1alpha3/clientintents_types.go
src/operator/api/v1beta1/clientintents_types.go
src/operator/api/v2alpha1/clientintents_types.go
src/operator/api/v2beta1/clientintents_types.go
src/operator/controllers/intents_reconcilers/cloud_reconciler_test.go

This PR fixes a bug where, when the `MissingSidecarAnnotation` is for whatever reason missing on the ClientIntents, reporting the ClientIntent to Otterize cloud would fail.

Fix bug where reporting applied intents to the cloud could fail when using istio, due to a missing MissingSidecarAnnotation annotation

---

src/operator/controllers/linkerd/linkerd_manager.go

This PR removes an overly verbose warning-level event with reason ShouldNotCreatePolicy, reported when linkerd support is enabled but enforcement is disabled. This is a valid situation and no warning events should be omitted in that case.

Remove overly verbose ShouldNotCreatePolicy when linkerd is enabled but enforcement is disabled

---

src/operator/controllers/external_traffic/network_policy.go
src/operator/controllers/intents_reconcilers/external_traffic_network_policy/external_traffic_network_policy_test.go
src/operator/controllers/intents_reconcilers/external_traffic_network_policy/external_traffic_network_policy_with_ingress_controllers_configured_test.go
src/shared/testbase/mocks_tests_suite_base.go
src/shared/testbase/testsuitebase.go

This PR removes an overly verbose event with reason ReasonEnforcementGloballyDisabled, reported when external traffic policy support is disabled. 
The PR also fixes the formatting of the events (to start with capital case, to meed conventions).

Remove overly verbose event ReasonEnforcementGloballyDisabled in allowexternaltraffic.Off mode & improve event messages

---

.github/workflow-helpers/prometheus-test-client-intents.yaml
.github/workflow-helpers/prometheus-test-deployment.yaml
.github/workflows/netpol-e2e-test.yaml
.github/workflows/test-bashrc.sh
src/operator/controllers/external_traffic/network_policy.go
src/operator/controllers/external_traffic/network_policy_test.go
src/operator/controllers/intents_reconcilers/external_traffic_network_policy/external_traffic_network_policy_test.go
src/operator/controllers/intents_reconcilers/external_traffic_network_policy/external_traffic_network_policy_with_ingress_controllers_configured_test.go
src/operator/controllers/intents_reconcilers/external_traffic_network_policy/external_traffic_network_policy_with_no_intents_test.go
src/operator/controllers/metrics_collection_traffic/network_policy_handler.go
src/operator/controllers/metrics_collection_traffic/network_policy_handler_test.go
src/operator/main.go
src/shared/operator_cloud_client/status_report.go
src/shared/operatorconfig/automate_third_party_network_policy/automate_third_party_network_policy_enum.go
src/shared/operatorconfig/enforcement/config.go
src/shared/otterizecloud/graphqlclient/generated.go
src/shared/otterizecloud/graphqlclient/schema.graphql
src/shared/telemetries/telemetriesgql/generated.go
src/shared/telemetries/telemetriesgql/schema.graphql

By setting intentsOperator.operator.automateThirdPartyNetworkPolicies and intentsOperator.operator.metricsScrapingServiceConfigs - Otterize can now automatically enable traffic from Prometheus server to any other workload marked with `prometheus.io/scrape` annotation.
You no longer have to create client-intents from the scraping server to your workloads.
- [Network mapper support](https://github.com/otterize/network-mapper/pull/278)
- [Helm chart support](https://github.com/otterize/helm-charts/pull/295)
- [Documentations](https://github.com/otterize/docs/pull/292)
Unit tests & e2e test were added

Automatically create network policies to allow Prometheus scraping traffic for workloads annotated with `prometheus.io/scrape`

---

src/operator/controllers/intents_reconcilers/database/database_reconciler.go

Fix a bug where, when performing reconcile on database intents applied to pods with no annotations, the operator could fail to add otterize annotations to the pod.

Fix bug where reconciling database intents would fail on pods with empty annotations

---

src/operator/webhooks/clientintents_webhook_v2alpha1.go
src/operator/webhooks/clientintents_webhook_v2beta1.go
src/operator/webhooks/strict_mode_helpers.go
src/operator/webhooks/webhook_suite_test.go
src/shared/operator_cloud_client/status_report.go
src/shared/operatorconfig/enforcement/config.go
src/shared/otterizecloud/graphqlclient/generated.go
src/shared/otterizecloud/graphqlclient/genqlient.graphql
src/shared/otterizecloud/graphqlclient/schema.graphql
src/shared/telemetries/telemetriesgql/schema.graphql

Added support for intents in strict mode. Webhook should enforce the following scenarios if strict mode is enabled:
* Internet intents should not allow wildcards
* Internet intents should not be allowed without port specified
* Only intents with type `Service` (or `kind: Service` in type `Kubernetes`) are allowed

Add support for intents in strict mode

---

src/operator/api/v2alpha1/clientintents_types.go
src/operator/controllers/webhook_traffic/custom_resource_definition_reconciler.go
src/operator/controllers/webhook_traffic/endpoints_reconciler.go
src/operator/controllers/webhook_traffic/mutating_webhooks_reconciler.go
src/operator/controllers/webhook_traffic/network_policies_reconciler.go
src/operator/controllers/webhook_traffic/network_policy_handler.go
src/operator/controllers/webhook_traffic/network_policy_handler_test.go
src/operator/controllers/webhook_traffic/network_policy_handler_utils_test.go
src/operator/controllers/webhook_traffic/services_reconciler.go
src/operator/controllers/webhook_traffic/validating_webhooks_reconciler.go
src/operator/controllers/webhook_traffic/webhook_traffic_reconciler_manager.go
src/operator/main.go
src/shared/operatorconfig/config.go

Based on the `AutomateThirdPartyNetworkPolicy` configuration, we will create a network policy to allow communication from the control plane to a webhook service.
This kind of communication is important, because if blocked - it may cause a lot of damage in the cluster, such as pods not being able to start.

[Prep for] Auto allow network traffic from control plane to webhook service

---

src/operator/controllers/webhook_traffic/custom_resource_definition_reconciler.go
src/shared/operator_cloud_client/status_report.go
src/shared/otterizecloud/graphqlclient/generated.go
src/shared/otterizecloud/graphqlclient/schema.graphql
src/shared/telemetries/telemetriesgql/schema.graphql

Report the AutomatedThirdPartyPolicyTypes to Otterize cloud, so Otterize cloud would be able to support auto-allow-webhook-traffic in shadow mode.
- [Reporting webhook services to Otterize cloud](https://github.com/otterize/network-mapper/pull/303)

[Prep for] Auto allow webhook traffic - support reporting AutomatedThirdPartyPolicyTypes to Otterize cloud for shadow mode support in cloud

---

src/operator/controllers/webhook_traffic/network_policy_handler.go
src/operator/controllers/webhook_traffic/network_policy_handler_test.go
src/operator/controllers/webhook_traffic/network_policy_handler_utils_test.go
src/operator/main.go
src/shared/operatorconfig/config.go

Improvements for allow webhook traffic feature:
1. Support IPv6 for control plane
2. Get control plane CIDR prefix length from configuration
3. Determine whether to restrict the network policy traffic source to the control plane IP based on configuration (by default - allow all)

[Prep for] Auto allow webhook traffic - restrict traffic from control plane IP based on configuration & support IPv6 for control plane
